(()=>{
'use strict';
const lessons=window.STUDY_LESSONS||[];
const guides=window.STUDY_GUIDES||{};
const codeTodos=window.STUDY_CODE_TODOS||{};
const visuals=window.STUDY_VISUALS||{};
let railObserver=null;
const widgets=window.STUDY_WIDGETS||{};
const codeLessonCount=lessons.filter(lesson=>codeTodos[lesson.id]).length;
const main=document.getElementById('main');
const storeKey='cs336-a1-guided-study-v1';
const originalRepo='https://github.com/stanford-cs336/assignment1-basics/tree/main';
const chapterNames={
 '01':'Assignment overview','02':'BPE tokenizer','03':'Transformer architecture','04':'Training mathematics','05':'Training loop','06':'Generating text','07':'Experiments'
};
const chapterVisuals={'01':'system','02':'bpe','03':'model','04':'math','05':'training','06':'generation','07':'experiments'};
const visualLessons={orientation:'system',unicode:'corpus','bpe-train':'bpe','tokenizer-exp':'encoded','full-lm':'model','cross-entropy':'math','train-loop':'training',generation:'generation',ablations:'experiments'};
const visualDescriptions={system:'Text → bytes → token IDs → model logits. Training links loss, updates, and checkpoints.',corpus:'UTF-8 example: A becomes hex 41; é becomes C3 A9. One character may require several bytes.',bpe:'A toy merge sequence: l + o + w → lo + w → low. Actual merges depend on corpus frequencies.',encoded:'Illustrative token IDs. Each target is the next token after its input; windows feed the model.',model:'Token IDs enter embeddings and causal Transformer blocks, then a head produces logits of shape (B,T,V).',math:'Target-token cross-entropy produces a scalar loss; gradients tell the optimizer how weights affect it.',training:'Batch → forward pass → loss and gradients → optimizer update. Checkpoints preserve the run state.',generation:'Sample a next token, append it to the prompt, and repeat. This distribution is illustrative.',experiments:'Compare validation-loss curves under controlled settings. These schematic curves are not assignment results.'};
const chapterFlow={
 '01':{input:'Handout + tests',output:'Build plan',next:'Tokenizer and model modules'},
 '02':{input:'UTF-8 source text',output:'Vocabulary, merges, token IDs',next:'Data sampler and LM'},
 '03':{input:'Token-ID windows',output:'Next-token logits (B,T,V)',next:'Loss and generation'},
 '04':{input:'Logits + targets',output:'Loss and update rules',next:'Training loop'},
 '05':{input:'Data + model + optimizer',output:'Checkpoints and learning curves',next:'Generation and experiments'},
 '06':{input:'Prompt + trained checkpoint',output:'Generated token sequence',next:'Qualitative evaluation'},
 '07':{input:'Working pipeline + logs',output:'Comparisons and submission',next:'Writeup + code archive'}
};
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readState(){try{const saved=JSON.parse(localStorage.getItem(storeKey)||'{}');return {current:typeof saved.current==='string'?saved.current:null,done:Array.isArray(saved.done)?saved.done:[]}}catch{return {current:null,done:[]}}}
let state=readState();
function saveState(){try{localStorage.setItem(storeKey,JSON.stringify(state))}catch{}}
function go(hash){if(location.hash===hash){render()}else{location.hash=hash}}
function chapterNum(lesson){return lesson.chapter.slice(0,2)}
const chapterIconPaths={
 '01':'M3 6.5l6-2.5 6 2.5 6-2.5v13.5l-6 2.5-6-2.5-6 2.5zM9 4v13.5M15 6.5V20',
 '02':'M3 7h5v10H3zM10 7h4v10h-4zM16 7h5v10h-5z',
 '03':'M4 4h16v4H4zM4 10h16v4H4zM4 16h16v4H4z',
 '04':'M17 5H7l6 7-6 7h10',
 '05':'M20 12a8 8 0 1 1-2.3-5.7M20 4v5h-5',
 '06':'M4 7h11M4 12h8M4 17h10M18.5 9v10M16.5 9h4M16.5 19h4',
 '07':'M9 3h6M10 3v6l-5 9.2A1.9 1.9 0 0 0 6.7 21h10.6a1.9 1.9 0 0 0 1.7-2.8L14 9V3M7.4 15h9.2'
};
function chapterIcon(n){return `<span class="chapter-icon" title="Chapter ${n}"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${chapterIconPaths[n]||''}"/></svg><span class="visually-hidden">Chapter ${n}</span></span>`}
function projectStructureMarkup(){return `<section class="overview-block project-structure" aria-labelledby="project-structure-heading"><p class="eyebrow">Repository structure</p><h2 class="section-title" id="project-structure-heading">One implementation, two paths</h2><p class="structure-intro">These are logical responsibilities, not prescribed filenames. The source repository supplies the test harness; you build the modules and scripts it calls.</p><div class="structure-core"><code>cs336_basics/</code><strong>Your reusable code</strong><span>Tokenizer · Transformer · loss and optimizer · data utilities</span></div><div class="structure-branches"><div class="structure-branch"><span class="branch-marker">↳ TEST PATH</span><code>tests/adapters.py</code><p>Connects your functions and classes to staff tests. Tests check component behavior.</p></div><div class="structure-branch"><span class="branch-marker">↳ RUN PATH</span><strong>Training and generation scripts</strong><p>Compose the same modules into experiments, checkpoints, curves, and samples.</p></div></div><div class="structure-output"><span>Evidence to submit</span><code>writeup.pdf</code><span>+</span><code>code.zip</code></div></section>`}
function overview(){
 const allProblems=lessons.flatMap(l=>l.problems);
 const groups=Object.keys(chapterNames).map(n=>({n,name:chapterNames[n],items:lessons.filter(l=>chapterNum(l)===n),problems:lessons.filter(l=>chapterNum(l)===n).flatMap(l=>l.problems)}));
 const done=lessons.filter(l=>state.done.includes(l.id)).length;
 const continueLesson=lessons.find(l=>l.id===state.current);
 main.className='overview-shell';
 main.innerHTML=`<div class="study-layout">${directoryMarkup(continueLesson?lessons.indexOf(continueLesson):-1,true)}<div class="overview">
 <p class="eyebrow">Stanford · Spring 2026 · Assignment 1</p><h1 class="hero-title"><span class="hero-course">CS336</span><span class="hero-name">Language Modeling<em>from Scratch</em></span></h1><p class="hero-tagline" aria-label="from byte to AI"><span aria-hidden="true">from</span><span class="tg-byte" aria-hidden="true">byte</span><span class="tg-flow" aria-hidden="true"><i>62</i><i>79</i><i>74</i><i>65</i><b></b></span><span aria-hidden="true">to</span><span class="tg-ai" aria-hidden="true">AI</span></p><p class="lede">Build a byte-level tokenizer, a Transformer language model, and its training loop yourself — seven stages, 31 short lessons, each tied to its handout page and tests.</p>
 <div class="intro-actions">${continueLesson?`<button class="primary-button" id="continue-learning" type="button">Continue: ${escapeHTML(continueLesson.title)} →</button><button class="secondary-button" id="start-learning" type="button">Start from lesson 1</button>`:`<button class="primary-button" id="start-learning" type="button">Start learning →</button>`}<div class="hero-progress" role="progressbar" aria-label="Lessons complete" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${lessons.length}"><span><strong>${done}</strong> / ${lessons.length} lessons complete</span><i><b style="width:${(done/lessons.length*100).toFixed(1)}%"></b></i></div>${continueLesson||done?'<button class="text-button" id="reset-overview" type="button">Reset progress</button>':''}</div>
 <section class="overview-block" aria-labelledby="path-heading"><h2 class="section-title" id="path-heading">The learning path</h2><p class="section-intro">Seven stages in build order. Each stage turns its input into the artifact the next stage needs — open a card to start that stage.</p>
 <ol class="stage-grid">${groups.map((g,k)=>{const completed=g.items.filter(l=>state.done.includes(l.id)).length;const flow=chapterFlow[g.n];return `<li class="stage-card${k===0?' stage-wide':''}"><a href="#lesson/${g.items[0].id}"><div class="stage-top">${chapterIcon(g.n)}<div><small>Stage ${k+1}</small><strong>${escapeHTML(g.name)}</strong></div><span class="stage-done">${completed}/${g.items.length}</span></div><img src="assets/visuals/${chapterVisuals[g.n]}.svg" width="480" height="280" alt="" loading="lazy">${k===0?'<p class="stage-blurb">Start here: see the whole pipeline on one page — what you implement, what you run, and what you hand in.</p>':''}<div class="stage-io"><span>${escapeHTML(flow.input)}</span><b aria-hidden="true">→</b><span>${escapeHTML(flow.output)}</span></div><div class="stage-meta">${g.items.length} lesson${g.items.length===1?'':'s'}${g.problems.length?` · ${g.problems.length} Problem${g.problems.length===1?'':'s'}`:''} · PDF ${escapeHTML(g.items[0].section)}</div><div class="stage-bar" aria-hidden="true"><b style="width:${(completed/g.items.length*100).toFixed(1)}%"></b></div></a></li>`}).join('')}</ol>
 <details class="problem-details"><summary>All ${allProblems.length} handout Problems by stage</summary><div class="problem-groups">${groups.map(g=>`<div><h3>${chapterIcon(g.n)} ${escapeHTML(g.name)}</h3><p>${g.problems.length?g.problems.map(p=>`<span class="problem-id">${escapeHTML(p)}</span>`).join(''):'No numbered Problem in this stage.'}</p></div>`).join('')}</div></details></section>
 ${projectStructureMarkup()}
 <section class="overview-block source-block"><div class="notice"><strong>Academic integrity:</strong> This unofficial, AI-assisted guide shows the official unimplemented adapter TODOs and conceptual hints. Complete and submit all code, experiments, and answers yourself, and follow the <a href="https://cs336.stanford.edu/" target="_blank" rel="noopener">course AI policy</a>. <a href="about.html">Read the full disclosure</a>.</div><p class="source-note">The 47-page Spring 2026 handout (v26.0.3) is bundled with this site and is the source of truth for requirements and submission rules. <a href="assets/handout.pdf" target="_blank" rel="noopener">Open the handout ↗</a> <a href="${originalRepo}" target="_blank" rel="noopener">Stanford GitHub repository ↗</a></p></section>
 </div></div>`;
 document.getElementById('start-learning').addEventListener('click',()=>go('#lesson/'+lessons[0].id));
 document.getElementById('continue-learning')?.addEventListener('click',()=>go('#lesson/'+continueLesson.id));
 document.getElementById('reset-overview')?.addEventListener('click',resetProgress);
 document.title='CS336 · Language Modeling from Scratch · Assignment 1';
}
// Left-hand contents. index is the current lesson (-1 for none); on the overview it only marks where to continue.
function directoryContent(index,onOverview){
 const current=lessons[index];const openChapter=current?chapterNum(current):null;
 const chapters=Object.keys(chapterNames).map(n=>({n,name:chapterNames[n],items:lessons.map((lesson,i)=>({lesson,i})).filter(x=>chapterNum(x.lesson)===n)}));
 return `<div class="directory-top"><a class="directory-home${onOverview?' current':''}" href="#overview">Overview</a><button class="toc-hide" type="button" data-toc-toggle aria-label="Hide contents" title="Hide contents"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 6l-6 6 6 6M4 4v16"/></svg></button></div><p class="toc-legend"><span>Underlined</span> = Python task</p><nav aria-label="All lessons">${chapters.map(group=>{const completed=group.items.filter(({lesson})=>state.done.includes(lesson.id)).length;const active=openChapter===group.n;return `<details class="toc-chapter"${active&&!onOverview?' open':''}><summary class="toc-chapter-title${active?' active':''}">${chapterIcon(group.n)}<span class="toc-chapter-name">${escapeHTML(group.name)}</span><span class="toc-chapter-count">${completed}/${group.items.length}</span></summary><ol>${group.items.map(({lesson,i})=>`<li><a data-toc-lesson-id="${lesson.id}" class="toc-lesson${i===index&&!onOverview?' current':''}${state.done.includes(lesson.id)?' completed':''}${codeTodos[lesson.id]?' has-code':''}" href="#lesson/${lesson.id}" ${i===index&&!onOverview?'aria-current="page"':''}><span class="toc-index">${String(i+1).padStart(2,'0')}</span><span class="toc-name">${escapeHTML(lesson.title)}${codeTodos[lesson.id]?'<span class="sr-only"> — Python task</span>':''}</span><span class="toc-check" aria-hidden="true">${state.done.includes(lesson.id)?'✓':''}</span></a></li>`).join('')}</ol></details>`}).join('')}</nav>`;
}
// Desktop contents can be hidden; the choice is remembered per browser.
const tocKey='cs336-a1-toc-hidden';
function setTocHidden(hidden){document.documentElement.dataset.toc=hidden?'hidden':'shown';try{localStorage.setItem(tocKey,hidden?'1':'0')}catch{}}
try{if(localStorage.getItem(tocKey)==='1')document.documentElement.dataset.toc='hidden'}catch{}
document.addEventListener('click',e=>{if(e.target.closest('[data-toc-toggle]'))setTocHidden(document.documentElement.dataset.toc!=='hidden')});
function directoryMarkup(index,onOverview=false){const content=directoryContent(index,onOverview);const where=onOverview?'overview':`lesson ${index+1} of ${lessons.length}`;return `<aside class="desktop-directory" aria-label="Contents">${content}</aside><button class="toc-show" type="button" data-toc-toggle><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h10"/></svg>Contents</button><details class="mobile-directory"><summary>Contents · ${lessons.length} lessons · ${where}</summary><div class="mobile-directory-content">${content}</div></details>`}
function resetProgress(){if(confirm('Reset saved lesson progress on this browser?')){state={current:null,done:[]};saveState();go('#overview')}}
const noteColors={red:'#8c1515',blue:'#2f5d8a',green:'#426550',gold:'#a8660f'};
function colorTex(tex,notes){for(const n of notes){const from=n.after?tex.indexOf(n.after)+n.after.length:0;const at=tex.indexOf(n.sym,from);if(from<0||at<0)continue;tex=tex.slice(0,at)+`\\textcolor{${noteColors[n.color]}}{${n.sym}}`+tex.slice(at+n.sym.length)}return tex}
// Escapes prose and renders any $...$ segments as inline KaTeX.
function richText(text){return String(text??'').split(/(\$[^$]+\$)/).map(part=>{if(part.length>2&&part.startsWith('$')&&part.endsWith('$')){try{return katex.renderToString(part.slice(1,-1),{throwOnError:false,output:'htmlAndMathml'})}catch{return `<code>${escapeHTML(part)}</code>`}}return escapeHTML(part)}).join('')}
function formulaCard(f,notes){let rendered;const tex=notes?colorTex(f.tex,notes):f.tex;try{rendered=katex.renderToString(tex,{displayMode:true,throwOnError:false,output:'htmlAndMathml',strict:'warn'})}catch{rendered=`<code>${escapeHTML(f.tex)}</code>`}
 const numbered=typeof f.number==='number';const label=numbered?`Handout equation (${f.number})`:'Concept relation';
 return `<div class="equation-card"><div class="equation-head"><span>${label}</span><span>${numbered?`(${f.number})`:'Study note'}</span></div><div class="equation-body" role="math" aria-label="${escapeHTML(f.tex)}">${rendered}</div>${notes?`<ul class="equation-key">${notes.map(n=>`<li style="--key:${noteColors[n.color]}">${escapeHTML(n.label)}</li>`).join('')}</ul>`:''}<div class="equation-notes"><p><strong>Read it:</strong> ${richText(f.explain)}</p><p><strong>Symbols and shapes:</strong> ${richText(f.symbols)}</p>${f.watch?`<p class="watch"><strong>Watch for:</strong> ${richText(f.watch)}</p>`:''}</div></div>`}
function codeTodoMarkup(lesson,guide){const todo=codeTodos[lesson.id];
 if(!todo)return `<div class="no-code-task"><strong>No required Python TODO in this section.</strong><p>${escapeHTML(guide.scope)}</p><ul>${guide.tasks.map(task=>`<li>${escapeHTML(task)}</li>`).join('')}</ul></div>`;
 if(todo.kind==='official')return `<p class="code-location"><strong>Where to work:</strong> ${escapeHTML(todo.where)}</p><p class="code-provenance">Exact source: Stanford <code>tests/adapters.py</code>. Each preview shows the original signature and its <code>raise NotImplementedError</code> line; expand it for the complete function.</p>${todo.blocks.map(block=>`<div class="stub-card"><div class="stub-head"><strong>${escapeHTML(block.name)}</strong><span class="todo-line-no">TODO L${block.todoLine}</span><a href="${escapeHTML(block.url)}" target="_blank" rel="noopener">Official source L${block.start}–${block.end} ↗</a></div><pre class="stub-signature"><code>${escapeHTML(block.signature)}</code></pre><p class="source-omission">Official documentation and comments omitted in preview</p><pre class="stub-todo"><code>${escapeHTML(block.todo)}</code></pre><details class="full-stub"><summary>View complete official function · ${block.end-block.start+1} lines</summary><pre><code>${escapeHTML(block.full)}</code></pre></details></div>`).join('')}`;
 return `<p class="code-location"><strong>Where to work:</strong> ${escapeHTML(todo.where)}</p><p class="code-provenance"><strong>Source:</strong> <a href="${escapeHTML(todo.url)}" target="_blank" rel="noopener">${escapeHTML(todo.source)}</a> The Python TODO scaffold below was written for this guide; Stanford does not prescribe its filename or signature.</p><pre class="suggested-code"><code>${escapeHTML(todo.code)}</code></pre>`;
}
function buildGuide(lesson){const guide=guides[lesson.id];if(!guide)return '';
 const first=`hint-principle-${lesson.id}`,second=`hint-pseudocode-${lesson.id}`,hasCode=Boolean(codeTodos[lesson.id]);
 return `<section class="lesson-section build-section" id="code" aria-labelledby="build-heading"><div class="build-heading"><h2 id="build-heading">${hasCode?'Python TODO':'Section task'}</h2><span>${hasCode?'Code required':'No required code'}</span></div><div class="build-layout"><div class="code-task-area">${codeTodoMarkup(lesson,guide)}</div><aside class="hint-flow" aria-label="Progressive hints"><strong class="hint-title">Hints, one layer at a time</strong><button class="hint-button" type="button" data-hint-toggle="principle" aria-controls="${first}" aria-expanded="false">Reveal level 1 · Principle</button><div class="hint-panel" id="${first}" hidden><p>${escapeHTML(guide.principle)}</p><button class="hint-button" type="button" data-hint-toggle="pseudocode" aria-controls="${second}" aria-expanded="false">Reveal level 2 · Pseudocode</button><div class="hint-panel pseudo-panel" id="${second}" hidden><pre><code>${escapeHTML(guide.pseudocode.join('\n'))}</code></pre><p class="hint-note">Use this outline to design your own implementation and verify it against the official handout.</p></div></div></aside></div></section>`}
function dependencyMarkup(lesson){const flow=chapterFlow[chapterNum(lesson)];return `<div class="lesson-flow" aria-label="How this stage connects to the project"><div><small>Stage input</small><strong>${escapeHTML(flow.input)}</strong></div><span aria-hidden="true">→</span><div><small>Chapter output</small><strong>${escapeHTML(flow.output)}</strong></div><span aria-hidden="true">→</span><div><small>Used next</small><strong>${escapeHTML(flow.next)}</strong></div></div>`}
function figureMarkup(fig,cls='figure extra-figure'){const c=fig.credit;
 return `<figure class="${cls}"><div class="figure-scroll"><img src="assets/diagrams/${escapeHTML(fig.src)}" alt="${escapeHTML(fig.alt)}" loading="lazy"></div><figcaption>${escapeHTML(fig.caption)}${c?`<span class="credit">Image: ${escapeHTML(c.author)}, <a href="${escapeHTML(c.sourceUrl)}" target="_blank" rel="noopener">${escapeHTML(c.source)}</a> · <a href="${escapeHTML(c.licenseUrl)}" target="_blank" rel="noopener">${escapeHTML(c.license)}</a></span>`:''}</figcaption></figure>`}
function explainMarkup(l,v){const inline=v.inline||[];
 return l.explain.map((p,i)=>`<p>${escapeHTML(p)}</p>${inline.filter(f=>f.after===i).map(f=>figureMarkup(f,'inline-figure')).join('')}`).join('')}
const linkKinds={article:'Article',video:'Video',paper:'Paper',code:'Code'};
function linksMarkup(v){if(!v.links?.length)return '';
 return `<section class="lesson-section" id="links"><h2>See it explained elsewhere</h2><p class="section-lede">Hand-picked outside explanations. They open in a new tab and may use different notation from the handout. Some include code: read for understanding and follow the course AI and collaboration policy.</p><div class="link-cards">${v.links.map(k=>`<a class="link-card" href="${escapeHTML(k.url)}" target="_blank" rel="noopener"><span class="link-kind kind-${escapeHTML(k.kind)}">${linkKinds[k.kind]||'Link'}</span><strong>${escapeHTML(k.title)} ↗</strong><small>${escapeHTML(k.author)}</small>${k.note?`<span>${escapeHTML(k.note)}</span>`:''}</a>`).join('')}</div></section>`}
function lessonView(index){const l=lessons[index];const v=visuals[l.id]||{};state.current=l.id;saveState();const complete=state.done.includes(l.id);main.className='lesson-shell';
 const hasWidget=Boolean(v.widget&&widgets[v.widget]);const guide=guides[l.id];

 const sections=[['idea','Idea'],hasWidget||v.figures?.length?['try','Try it']:null,['points','Key points'],l.formulas.length?['equations','Mathematics']:null,guide?['code',codeTodos[l.id]?'Python TODO':'Section task']:null,['connection','Assignment'],v.links?.length?['links','Further reading']:null,['check','Check yourself']].filter(Boolean);
 main.innerHTML=`<div class="lesson-top"><strong class="lesson-chapter">${chapterIcon(chapterNum(l))}${escapeHTML(chapterNames[chapterNum(l)]||l.chapter)}</strong><span>Lesson ${String(index+1).padStart(2,'0')} of ${lessons.length}</span></div><div class="progress-bar" aria-hidden="true"><span style="width:${((index+1)/lessons.length*100).toFixed(1)}%"></span></div>
 <div class="study-layout">${directoryMarkup(index)}<article class="lesson"><p class="chapter-label">${escapeHTML(l.section)}</p><h1>${escapeHTML(l.title)}</h1><p class="goal">${escapeHTML(l.goal)}</p><div class="lesson-meta"><span>Handout page ${l.page}</span><a href="assets/handout.pdf#page=${l.page}" target="_blank" rel="noopener">Read this part in the PDF ↗</a><a href="${originalRepo}" target="_blank" rel="noopener">Original GitHub ↗</a></div>
 ${dependencyMarkup(l)}
 <figure class="figure"><div class="figure-scroll"><img src="assets/diagrams/${escapeHTML(l.diagram)}.svg" alt="Diagram: ${escapeHTML(l.title)}"></div><figcaption>${escapeHTML(l.diagramAlt)}</figcaption></figure>
 <section class="lesson-section" id="idea"><h2>Understand the idea</h2>${explainMarkup(l,v)}</section>
 ${hasWidget||v.figures?.length?`<section class="lesson-section" id="try">${hasWidget?`<div class="widget" data-widget="${escapeHTML(v.widget)}"></div>`:''}${(v.figures||[]).map(f=>figureMarkup(f)).join('')}</section>`:''}
 <section class="lesson-section" id="points"><h2>Keep these points in mind</h2><ul class="concept-list">${l.concepts.map(p=>`<li>${escapeHTML(p)}</li>`).join('')}</ul></section>
 ${l.formulas.length?`<section class="lesson-section" id="equations"><h2>Mathematics</h2>${l.formulas.map((f,i)=>formulaCard(f,v.formulaNotes?.[f.number??i])).join('')}</section>`:''}
 ${buildGuide(l)}
 <section class="lesson-section" id="connection"><h2>Assignment connection</h2><div class="assignment-box"><strong>${l.problems.length?`${l.problems.length} Problem${l.problems.length===1?'':'s'}`:'Foundation lesson'}</strong><div>${l.problems.map(p=>`<span class="problem-id">${escapeHTML(p)}</span>`).join('')}</div><p><strong>Check:</strong> ${escapeHTML(l.test)}</p></div></section>
 ${linksMarkup(v)}
 <section class="lesson-section" id="check"><h2>Check yourself</h2><ol class="check-list">${l.check.map(q=>`<li>${escapeHTML(q)}</li>`).join('')}</ol></section>
 <div class="lesson-actions"><label class="complete-label"><input id="complete-toggle" type="checkbox" ${complete?'checked':''}> Mark lesson complete</label><div class="nav-actions"><button class="secondary-button" id="back-button" type="button">← ${index===0?'Overview':'Back'}</button><button class="primary-button" id="next-button" type="button">${index===lessons.length-1?'Overview':'Next lesson →'}</button></div></div></article>
 <nav class="page-rail" aria-label="On this page"><strong>On this page</strong>${sections.map(([id,label])=>`<a href="#${id}" data-rail="${id}">${label}</a>`).join('')}</nav></div>`;
 main.querySelectorAll('[data-widget]').forEach(el=>{try{widgets[el.dataset.widget](el)}catch(err){el.remove();console.error(err)}});
 document.getElementById('complete-toggle').addEventListener('change',e=>{state.done=e.target.checked?[...new Set([...state.done,l.id])]:state.done.filter(id=>id!==l.id);saveState();main.querySelectorAll(`[data-toc-lesson-id="${l.id}"]`).forEach(a=>{a.classList.toggle('completed',e.target.checked);a.querySelector('.toc-check').textContent=e.target.checked?'✓':''})});
 // In-page links must not change the #lesson/... route, so scroll instead of navigating.
 main.querySelectorAll('[data-rail]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.getElementById(a.dataset.rail)?.scrollIntoView({block:'start',behavior:'smooth'})}));
 railObserver?.disconnect();
 if('IntersectionObserver' in window){railObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)main.querySelectorAll('[data-rail]').forEach(a=>a.classList.toggle('active',a.dataset.rail===entry.target.id))})},{rootMargin:'0px 0px -70% 0px'});sections.forEach(([id])=>{const el=document.getElementById(id);if(el)railObserver.observe(el)})}
 document.getElementById('back-button').addEventListener('click',()=>go(index===0?'#overview':'#lesson/'+lessons[index-1].id));
 document.getElementById('next-button').addEventListener('click',()=>go(index===lessons.length-1?'#overview':'#lesson/'+lessons[index+1].id));
 main.querySelector('.desktop-directory .toc-lesson.current')?.scrollIntoView({block:'nearest'});
 document.title=`${l.title} · CS336 Assignment 1`;
}
function render(){const match=location.hash.match(/^#lesson\/([a-z0-9-]+)$/);const index=match?lessons.findIndex(l=>l.id===match[1]):-1;if(index>=0)lessonView(index);else overview();window.scrollTo?.(0,0)}
document.getElementById('overview-button').addEventListener('click',()=>go('#overview'));
main.addEventListener('click',event=>{const button=event.target.closest('[data-hint-toggle]');if(!button||!main.contains(button))return;const panel=document.getElementById(button.getAttribute('aria-controls'));if(!panel)return;panel.hidden=!panel.hidden;const expanded=!panel.hidden;button.setAttribute('aria-expanded',String(expanded));button.textContent=`${expanded?'Hide':'Reveal'} level ${button.dataset.hintToggle==='principle'?'1 · Principle':'2 · Pseudocode'}`;if(button.dataset.hintToggle==='principle'&&!expanded){const nested=panel.querySelector('[data-hint-toggle="pseudocode"]'),nestedPanel=nested&&document.getElementById(nested.getAttribute('aria-controls'));if(nested&&nestedPanel){nestedPanel.hidden=true;nested.setAttribute('aria-expanded','false');nested.textContent='Reveal level 2 · Pseudocode'}}});
window.addEventListener('hashchange',render);
document.addEventListener('keydown',event=>{if(!event.altKey||event.ctrlKey||event.metaKey)return;const match=location.hash.match(/^#lesson\/([a-z0-9-]+)$/);const index=match?lessons.findIndex(l=>l.id===match[1]):-1;if(index<0)return;if(event.key==='ArrowRight'){event.preventDefault();go(index<lessons.length-1?'#lesson/'+lessons[index+1].id:'#overview')}if(event.key==='ArrowLeft'){event.preventDefault();go(index>0?'#lesson/'+lessons[index-1].id:'#overview')}});
if(!lessons.length){main.innerHTML='<div class="error">Lesson content could not be loaded. Check that lessons.js is beside this page.</div>'}else render();
})();
