(()=>{
'use strict';
const lessons=window.STUDY_LESSONS||[];
const guides=window.STUDY_GUIDES||{};
const codeTodos=window.STUDY_CODE_TODOS||{};
const codeLessonCount=lessons.filter(lesson=>codeTodos[lesson.id]).length;
const main=document.getElementById('main');
const storeKey='cs336-a1-guided-study-v1';
const originalRepo='https://github.com/stanford-cs336/assignment1-basics/tree/main';
const chapterNames={
 '01':'Assignment overview','02':'BPE tokenizer','03':'Transformer architecture','04':'Training mathematics','05':'Training loop','06':'Generating text','07':'Experiments'
};
const chapterVisuals={'01':'system','02':'bpe','03':'model','04':'math','05':'training','06':'generation','07':'experiments'};
const visualLessons={orientation:'system',unicode:'corpus','bpe-train':'bpe','tokenizer-exp':'encoded','full-lm':'model','cross-entropy':'math','train-loop':'training',generation:'generation',ablations:'experiments'};
const visualDescriptions={system:'Text → bytes → token IDs → model logits. Training links loss, updates, and checkpoints.',corpus:'UTF-8 example: A becomes hex 41; é becomes C3 A9. One character may require several bytes.',bpe:'A toy merge sequence: l + o + w → lo + w → low. Actual merges depend on corpus frequencies.',encoded:'Illustrative token IDs. Each target is the next token after its input; windows feed the model.',model:'Token IDs enter embeddings and causal Transformer blocks, then a head produces logits of shape (B,T,V).',math:'Target-token cross-entropy produces a scalar loss; gradients tell the optimizer how weights affect it.',training:'Batch → forward pass → loss and gradients → optimizer update. Checkpoints preserve the run state.',generation:'Sample a next token, append it to the prompt, and repeat. This distribution is illustrative.',experiments:'Compare validation-loss curves under controlled settings. These schematic curves are not assignment results.'};
const chapterFlow={
 '01':{input:'Handout + tests',output:'Build plan',next:'Tokenizer and model modules'},
 '02':{input:'UTF-8 source text',output:'Vocabulary, merges, token IDs',next:'Data sampler and LM'},
 '03':{input:'Token-ID windows',output:'Next-token logits (B,T,V)',next:'Loss and generation'},
 '04':{input:'Logits + targets',output:'Loss and update rules',next:'Training loop'},
 '05':{input:'Data + model + optimizer',output:'Checkpoints and learning curves',next:'Generation and experiments'},
 '06':{input:'Prompt + trained checkpoint',output:'Generated token sequence',next:'Qualitative evaluation'},
 '07':{input:'Working pipeline + logs',output:'Comparisons and submission',next:'Writeup + code archive'}
};
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readState(){try{const saved=JSON.parse(localStorage.getItem(storeKey)||'{}');return {current:typeof saved.current==='string'?saved.current:null,done:Array.isArray(saved.done)?saved.done:[]}}catch{return {current:null,done:[]}}}
let state=readState();
function saveState(){try{localStorage.setItem(storeKey,JSON.stringify(state))}catch{}}
function go(hash){if(location.hash===hash){render()}else{location.hash=hash}}
function chapterNum(lesson){return lesson.chapter.slice(0,2)}
function architectureMarkup(){
 const stages=[
  {n:'01',title:'Text corpus',input:'Source documents',output:'UTF-8 bytes',lesson:'unicode',visual:'corpus',detail:'Decide what the tokenizer sees.'},
  {n:'02',title:'BPE tokenizer',input:'Bytes + corpus',output:'Vocabulary + merges',lesson:'bpe-train',visual:'bpe',detail:'Learn reusable byte spans.'},
  {n:'03',title:'Encoded data',input:'Text + tokenizer',output:'Token-ID arrays',lesson:'tokenizer-exp',visual:'encoded',detail:'Prepare train and validation streams.'},
  {n:'04',title:'Transformer LM',input:'Token windows (B,T)',output:'Logits (B,T,V)',lesson:'full-lm',visual:'model',detail:'Predict every next token.'}
 ];
 return `<section class="overview-block architecture-block" aria-labelledby="architecture-heading"><div class="architecture-heading"><div><p class="eyebrow">System architecture</p><h2 id="architecture-heading">How the pieces connect</h2></div><p>Each output becomes an input to the next stage. Select a card to open its lesson.</p></div>
 <div class="architecture-track" aria-label="Data path from text to model logits">${stages.map(s=>`<a class="arch-stage" href="#lesson/${s.lesson}"><span class="arch-number">${s.n} / DATA PATH</span><strong>${s.title}</strong><img class="stage-visual" src="assets/visuals/${s.visual}.svg" width="480" height="280" alt="${escapeHTML(visualDescriptions[s.visual])}"><small>${s.detail}</small><span class="arch-contract"><span>${s.input}</span><span aria-hidden="true">→</span><b>${s.output}</b></span></a>`).join('')}</div>
 <div class="model-strip"><span class="strip-label">Inside the Transformer</span><a href="#lesson/linear-embedding">Embedding</a><span aria-hidden="true">→</span><a href="#lesson/mha">RoPE attention</a><span aria-hidden="true">→</span><a href="#lesson/swiglu">SwiGLU + residual blocks</a><span aria-hidden="true">→</span><a href="#lesson/full-lm">LM head</a></div>
 <div class="architecture-lanes"><div class="arch-lane train-lane"><span class="lane-label">Training · updates the model ↺</span><p><a href="#lesson/data">Batch windows</a> → <a href="#lesson/cross-entropy">loss</a> → gradients → <a href="#lesson/adamw">AdamW</a> → new weights</p><small><a href="#lesson/checkpoint">Checkpoints</a> and validation preserve evidence of the run.</small></div><div class="arch-lane generate-lane"><span class="lane-label">Generation · uses the trained model →</span><p>Prompt IDs → last logits → <a href="#lesson/generation">temperature + top-p</a> → next ID → text</p><small>Sampling repeats until an end token or length limit.</small></div></div>
 <div class="architecture-outcome"><span class="lane-label">Then measure and compare</span><span><a href="#lesson/tinystories">TinyStories baseline</a> → <a href="#lesson/ablations">architecture ablations</a> → <a href="#lesson/owt">OpenWebText</a> → <a href="#lesson/leaderboard">submission</a></span></div></section>`;
}
function projectStructureMarkup(){return `<section class="overview-block project-structure" aria-labelledby="project-structure-heading"><p class="eyebrow">Repository structure</p><h2 class="section-title" id="project-structure-heading">One implementation, two paths</h2><p class="structure-intro">These are logical responsibilities, not prescribed filenames. The source repository supplies the test harness; you build the modules and scripts it calls.</p><div class="structure-core"><code>cs336_basics/</code><strong>Your reusable code</strong><span>Tokenizer · Transformer · loss and optimizer · data utilities</span></div><div class="structure-branches"><div class="structure-branch"><span class="branch-marker">↳ TEST PATH</span><code>tests/adapters.py</code><p>Connects your functions and classes to staff tests. Tests check component behavior.</p></div><div class="structure-branch"><span class="branch-marker">↳ RUN PATH</span><strong>Training and generation scripts</strong><p>Compose the same modules into experiments, checkpoints, curves, and samples.</p></div></div><div class="structure-output"><span>Evidence to submit</span><code>writeup.pdf</code><span>+</span><code>code.zip</code></div></section>`}
function overview(){
 const allProblems=lessons.flatMap(l=>l.problems);
 const groups=Object.keys(chapterNames).map(n=>({n,name:chapterNames[n],items:lessons.filter(l=>chapterNum(l)===n),problems:lessons.filter(l=>chapterNum(l)===n).flatMap(l=>l.problems)}));
 const done=lessons.filter(l=>state.done.includes(l.id)).length;
 const numberedEquations=lessons.flatMap(l=>l.formulas).filter(f=>typeof f.number==='number').length;
 const maxProblems=Math.max(...groups.map(g=>g.problems.length));
 const continueLesson=lessons.find(l=>l.id===state.current);
 main.className='overview';
 main.innerHTML=`<figure class="campus-cover"><img src="assets/images/stanford-quad.jpg" width="6000" height="408" alt="Panoramic view of the sandstone arcades of Stanford Main Quad"><figcaption>Stanford Main Quad · Michael Connor · <a href="about.html#visual-credits">CC BY 2.5 / image credits</a></figcaption></figure><p class="eyebrow">Assignment 1 · system map</p><h1>From raw text to a trained language model.</h1><p class="lede">Follow the artifacts through the system, then study each component in the order it is built and tested.</p>
 <div class="intro-actions"><button class="primary-button" id="start-learning" type="button">Start learning →</button>${continueLesson?`<button class="secondary-button" id="continue-learning" type="button">Continue: ${escapeHTML(continueLesson.title)}</button>`:''}<span class="progress-note">${done} of ${lessons.length} lessons marked complete</span>${continueLesson||done?'<button class="text-button" id="reset-overview" type="button">Reset progress</button>':''}</div>
 <div class="overview-metrics" aria-label="Assignment coverage"><div class="metric progress-metric"><strong>${done}<span>/${lessons.length}</span></strong><small>lessons complete</small><div class="metric-track" role="progressbar" aria-label="Lessons complete" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="${lessons.length}"><span style="width:${(done/lessons.length*100).toFixed(1)}%"></span></div></div><div class="metric"><strong>${allProblems.length}</strong><small>Problem IDs</small></div><div class="metric"><strong>${numberedEquations}</strong><small>PDF equations</small></div><div class="metric"><strong>${codeLessonCount}</strong><small>Python task sections</small></div></div>
 ${architectureMarkup()}
 <section class="overview-block" aria-labelledby="required-heading"><h2 class="section-title" id="required-heading">Everything you need to do</h2><div class="requirements">
 <div class="requirement"><h3>1. Build the components</h3><ul><li>Train a byte-level BPE tokenizer and implement encoding, streaming, and decoding.</li><li>Build a decoder-only Transformer LM: embeddings, RMSNorm, SwiGLU, RoPE, causal multi-head attention, and blocks.</li><li>Implement cross-entropy, AdamW, learning-rate scheduling, and gradient clipping.</li><li>Build batching, checkpointing, a training loop, and text decoding.</li></ul></div>
 <div class="requirement"><h3>2. Run the pipeline</h3><ul><li>Train TinyStories and OpenWebText tokenizers; encode train and validation data.</li><li>Train and evaluate a TinyStories model; report validation loss and generated text.</li><li>Log learning curves, tune learning rate and batch size, and run four architecture ablations.</li><li>Train on OpenWebText and compare results; for full handout completion, run the leaderboard experiment under its constraints.</li></ul></div>
 <div class="requirement"><h3>3. Check the work</h3><ul><li>Connect your own modules through <code>tests/adapters.py</code>; do not change the staff tests.</li><li>Use <code>uv run pytest</code> and targeted tests as components are finished.</li><li>Record shapes, numerical checks, compute budgets, seeds, and experiment settings.</li></ul></div>
 <div class="requirement"><h3>4. Submit the evidence</h3><ul><li>A typeset <code>writeup.pdf</code> answering the written and experimental prompts.</li><li>A <code>code.zip</code> made with the repository’s submission script, excluding large data and checkpoints.</li><li>For leaderboard participation, a separate run record and submission following the official repository.</li></ul></div>
 </div><div class="notice"><strong>Academic integrity:</strong> This unofficial, AI-assisted guide shows the official unimplemented adapter TODOs and conceptual hints. Complete and submit all code, experiments, and answers yourself, and follow the <a href="https://cs336.stanford.edu/" target="_blank" rel="noopener">course AI policy</a>. <a href="about.html">Read the full disclosure</a>.</div></section>
 ${projectStructureMarkup()}
 <section class="overview-block" aria-labelledby="chapters-heading"><div class="chapter-list-heading"><div><p class="eyebrow">Learning sequence</p><h2 class="section-title" id="chapters-heading">The seven stages</h2></div><span>Bar length = Problem count · green = lessons completed</span></div><div class="chapter-list">${groups.map(g=>{const completed=g.items.filter(l=>state.done.includes(l.id)).length;return `<a class="chapter-row" href="#lesson/${g.items[0].id}"><span class="chapter-num">${g.n}</span><img class="chapter-thumbnail" src="assets/visuals/${chapterVisuals[g.n]}.svg" width="480" height="280" alt="" loading="lazy"><div class="chapter-summary"><strong>${escapeHTML(g.name)}</strong><small>${g.items.length} lessons · ${g.problems.length} Problems · PDF ${escapeHTML(g.items[0].section)}</small><div class="chapter-load" role="img" aria-label="${g.problems.length} Problems, ${completed} of ${g.items.length} lessons complete"><span class="problem-load" style="width:${(g.problems.length/maxProblems*100).toFixed(1)}%"></span><span class="completed-load" style="width:${(completed/g.items.length*100).toFixed(1)}%"></span></div></div><span class="chapter-count">${completed}/${g.items.length} done ↗</span></a>`}).join('')}</div>
 <details class="problem-details"><summary>View all ${allProblems.length} Problem IDs</summary><div class="problem-groups">${groups.map(g=>`<div><h3>${g.n} · ${escapeHTML(g.name)}</h3><p>${g.problems.length?g.problems.map(p=>`<span class="problem-id">${escapeHTML(p)}</span>`).join(''):'No numbered Problem in this chapter.'}</p></div>`).join('')}</div></details></section>
 <section class="overview-block"><h2 class="section-title">Your source of truth</h2><p class="lede" style="font-size:.9rem;margin-bottom:8px">The local 47-page Spring 2026 handout (v26.0.3) is bundled with this site. Every lesson links to its PDF page. Requirements and submission rules should be checked against that handout.</p><div class="source-links"><a href="${originalRepo}" target="_blank" rel="noopener">Original Stanford GitHub repository ↗</a><a href="assets/handout.pdf" target="_blank" rel="noopener">Open the assignment handout ↗</a></div></section>`;
 document.getElementById('start-learning').addEventListener('click',()=>go('#lesson/'+lessons[0].id));
 document.getElementById('continue-learning')?.addEventListener('click',()=>go('#lesson/'+continueLesson.id));
 document.getElementById('reset-overview')?.addEventListener('click',resetProgress);
 document.title='CS336 Assignment 1 · Overview';
}
function directoryContent(index){
 const current=lessons[index];
 const chapters=Object.keys(chapterNames).map(n=>({n,name:chapterNames[n],items:lessons.map((lesson,i)=>({lesson,i})).filter(x=>chapterNum(x.lesson)===n)}));
 return `<div class="directory-heading">All ${lessons.length} lessons</div><p class="directory-position">Now studying ${index+1} of ${lessons.length} · ${escapeHTML(current.section)}</p><p class="toc-legend"><span>Underlined</span> = Python task (${codeLessonCount})</p><button class="directory-math" data-scroll-formulas type="button">Mathematics in this lesson <span>${current.formulas.length} ↓</span></button><nav aria-label="All lessons">${chapters.map(group=>`<div class="toc-chapter"><div class="toc-chapter-title${chapterNum(current)===group.n?' active':''}"><img class="toc-thumbnail" src="assets/visuals/${chapterVisuals[group.n]}.svg" width="480" height="280" alt="" loading="lazy"><span>${group.n}</span>${escapeHTML(group.name)}</div><ol>${group.items.map(({lesson,i})=>`<li><a data-toc-lesson-id="${lesson.id}" class="toc-lesson${i===index?' current':''}${state.done.includes(lesson.id)?' completed':''}${codeTodos[lesson.id]?' has-code':''}" href="#lesson/${lesson.id}" ${i===index?'aria-current="step"':''}><span class="toc-index">${String(i+1).padStart(2,'0')}</span><span class="toc-name">${escapeHTML(lesson.title)}${codeTodos[lesson.id]?'<span class="sr-only"> — Python task</span>':''}</span><span class="toc-check" aria-hidden="true">${state.done.includes(lesson.id)?'✓':''}</span></a></li>`).join('')}</ol></div>`).join('')}</nav>`;
}
function directoryMarkup(index){const content=directoryContent(index);return `<aside class="desktop-directory" aria-label="All ${lessons.length} lessons">${content}</aside><details class="mobile-directory"><summary>All ${lessons.length} lessons · ${codeLessonCount} Python tasks · now at ${index+1}</summary><div class="mobile-directory-content">${content}</div></details>`}
function resetProgress(){if(confirm('Reset saved lesson progress on this browser?')){state={current:null,done:[]};saveState();go('#overview')}}
function formulaCard(f){let rendered;try{rendered=katex.renderToString(f.tex,{displayMode:true,throwOnError:false,output:'htmlAndMathml',strict:'warn'})}catch{rendered=`<code>${escapeHTML(f.tex)}</code>`}
 const numbered=typeof f.number==='number';const label=numbered?`Handout equation (${f.number})`:'Concept relation';
 return `<div class="equation-card"><div class="equation-head"><span>${label}</span><span>${numbered?`(${f.number})`:'Study note'}</span></div><div class="equation-body" role="math" aria-label="${escapeHTML(f.tex)}">${rendered}</div><div class="equation-notes"><p><strong>Read it:</strong> ${escapeHTML(f.explain)}</p><p><strong>Symbols and shapes:</strong> ${escapeHTML(f.symbols)}</p>${f.watch?`<p class="watch"><strong>Watch for:</strong> ${escapeHTML(f.watch)}</p>`:''}</div></div>`}
function codeTodoMarkup(lesson,guide){const todo=codeTodos[lesson.id];
 if(!todo)return `<div class="no-code-task"><strong>No required Python TODO in this section.</strong><p>${escapeHTML(guide.scope)}</p><ul>${guide.tasks.map(task=>`<li>${escapeHTML(task)}</li>`).join('')}</ul></div>`;
 if(todo.kind==='official')return `<p class="code-location"><strong>Where to work:</strong> ${escapeHTML(todo.where)}</p><p class="code-provenance">Exact source: Stanford <code>tests/adapters.py</code>. Each preview shows the original signature and its <code>raise NotImplementedError</code> line; expand it for the complete function.</p>${todo.blocks.map(block=>`<div class="stub-card"><div class="stub-head"><strong>${escapeHTML(block.name)}</strong><span class="todo-line-no">TODO L${block.todoLine}</span><a href="${escapeHTML(block.url)}" target="_blank" rel="noopener">Official source L${block.start}–${block.end} ↗</a></div><pre class="stub-signature"><code>${escapeHTML(block.signature)}</code></pre><p class="source-omission">Official documentation and comments omitted in preview</p><pre class="stub-todo"><code>${escapeHTML(block.todo)}</code></pre><details class="full-stub"><summary>View complete official function · ${block.end-block.start+1} lines</summary><pre><code>${escapeHTML(block.full)}</code></pre></details></div>`).join('')}`;
 return `<p class="code-location"><strong>Where to work:</strong> ${escapeHTML(todo.where)}</p><p class="code-provenance"><strong>Source:</strong> <a href="${escapeHTML(todo.url)}" target="_blank" rel="noopener">${escapeHTML(todo.source)}</a> The Python TODO scaffold below was written for this guide; Stanford does not prescribe its filename or signature.</p><pre class="suggested-code"><code>${escapeHTML(todo.code)}</code></pre>`;
}
function buildGuide(lesson){const guide=guides[lesson.id];if(!guide)return '';
 const first=`hint-principle-${lesson.id}`,second=`hint-pseudocode-${lesson.id}`,hasCode=Boolean(codeTodos[lesson.id]);
 return `<section class="lesson-section build-section" aria-labelledby="build-heading"><div class="build-heading"><h2 id="build-heading">${hasCode?'Python TODO':'Section task'}</h2><span>${hasCode?'Code required':'No required code'}</span></div><div class="build-layout"><div class="code-task-area">${codeTodoMarkup(lesson,guide)}</div><aside class="hint-flow" aria-label="Progressive hints"><strong class="hint-title">Hints, one layer at a time</strong><button class="hint-button" type="button" data-hint-toggle="principle" aria-controls="${first}" aria-expanded="false">Reveal level 1 · Principle</button><div class="hint-panel" id="${first}" hidden><p>${escapeHTML(guide.principle)}</p><button class="hint-button" type="button" data-hint-toggle="pseudocode" aria-controls="${second}" aria-expanded="false">Reveal level 2 · Pseudocode</button><div class="hint-panel pseudo-panel" id="${second}" hidden><pre><code>${escapeHTML(guide.pseudocode.join('\n'))}</code></pre><p class="hint-note">Use this outline to design your own implementation and verify it against the official handout.</p></div></div></aside></div></section>`}
function dependencyMarkup(lesson){const flow=chapterFlow[chapterNum(lesson)];return `<div class="lesson-flow" aria-label="How this stage connects to the project"><div><small>Stage input</small><strong>${escapeHTML(flow.input)}</strong></div><span aria-hidden="true">→</span><div><small>Chapter output</small><strong>${escapeHTML(flow.output)}</strong></div><span aria-hidden="true">→</span><div><small>Used next</small><strong>${escapeHTML(flow.next)}</strong></div></div>`}
function lessonView(index){const l=lessons[index];state.current=l.id;saveState();const complete=state.done.includes(l.id);main.className='lesson-shell';
 main.innerHTML=`<div class="lesson-top"><strong>${escapeHTML(l.chapter)}</strong><span>Lesson ${String(index+1).padStart(2,'0')} of ${lessons.length}</span></div><div class="progress-bar" aria-hidden="true"><span style="width:${((index+1)/lessons.length*100).toFixed(1)}%"></span></div>
 <div class="study-layout">${directoryMarkup(index)}<article class="lesson"><p class="chapter-label">${escapeHTML(l.section)}</p><h1>${escapeHTML(l.title)}</h1><p class="goal">${escapeHTML(l.goal)}</p><div class="lesson-meta"><span>Handout page ${l.page}</span><a href="assets/handout.pdf#page=${l.page}" target="_blank" rel="noopener">Read this part in the PDF ↗</a><a href="${originalRepo}" target="_blank" rel="noopener">Original GitHub ↗</a></div>
 ${dependencyMarkup(l)}
 ${visualLessons[l.id]?`<figure class="concept-visual"><img src="assets/visuals/${visualLessons[l.id]}.svg" width="480" height="280" alt="${escapeHTML(visualDescriptions[visualLessons[l.id]])}"><figcaption><strong>Visual intuition.</strong> ${escapeHTML(visualDescriptions[visualLessons[l.id]])}</figcaption></figure>`:''}
 <figure class="figure"><img src="assets/diagrams/${escapeHTML(l.diagram)}.svg" alt="${escapeHTML(l.diagramAlt)}"><figcaption>${escapeHTML(l.diagramAlt)}</figcaption></figure>
 ${buildGuide(l)}
 <section class="lesson-section"><h2>Understand the idea</h2>${l.explain.map(p=>`<p>${escapeHTML(p)}</p>`).join('')}</section>
 <section class="lesson-section"><h2>Keep these points in mind</h2><ul class="concept-list">${l.concepts.map(p=>`<li>${escapeHTML(p)}</li>`).join('')}</ul></section>
 ${l.formulas.length?`<section class="lesson-section" id="equations"><h2>Mathematics</h2>${l.formulas.map(formulaCard).join('')}</section>`:''}
 <section class="lesson-section"><h2>Assignment connection</h2><div class="assignment-box"><strong>${l.problems.length?`${l.problems.length} Problem${l.problems.length===1?'':'s'}`:'Foundation lesson'}</strong><div>${l.problems.map(p=>`<span class="problem-id">${escapeHTML(p)}</span>`).join('')}</div><p><strong>Check:</strong> ${escapeHTML(l.test)}</p></div></section>
 <section class="lesson-section"><h2>Check yourself</h2><ol class="check-list">${l.check.map(q=>`<li>${escapeHTML(q)}</li>`).join('')}</ol></section>
 <div class="lesson-actions"><label class="complete-label"><input id="complete-toggle" type="checkbox" ${complete?'checked':''}> Mark lesson complete</label><div class="nav-actions"><button class="secondary-button" id="back-button" type="button">← ${index===0?'Overview':'Back'}</button><button class="primary-button" id="next-button" type="button">${index===lessons.length-1?'Overview':'Next lesson →'}</button></div></div>
 <div class="reset-area"><span>Progress is saved only in this browser.</span><button class="text-button" id="reset-button" type="button">Reset progress</button></div></article></div>`;
 document.getElementById('complete-toggle').addEventListener('change',e=>{state.done=e.target.checked?[...new Set([...state.done,l.id])]:state.done.filter(id=>id!==l.id);saveState();main.querySelectorAll(`[data-toc-lesson-id="${l.id}"]`).forEach(a=>{a.classList.toggle('completed',e.target.checked);a.querySelector('.toc-check').textContent=e.target.checked?'✓':''})});
 main.querySelectorAll('[data-scroll-formulas]').forEach(button=>button.addEventListener('click',()=>document.getElementById('equations')?.scrollIntoView({block:'start',behavior:'smooth'})));
 document.getElementById('back-button').addEventListener('click',()=>go(index===0?'#overview':'#lesson/'+lessons[index-1].id));
 document.getElementById('next-button').addEventListener('click',()=>go(index===lessons.length-1?'#overview':'#lesson/'+lessons[index+1].id));
 document.getElementById('reset-button').addEventListener('click',resetProgress);
 document.title=`${l.title} · CS336 Assignment 1`;
}
function render(){const match=location.hash.match(/^#lesson\/([a-z0-9-]+)$/);const index=match?lessons.findIndex(l=>l.id===match[1]):-1;if(index>=0)lessonView(index);else overview();window.scrollTo?.(0,0)}
document.getElementById('overview-button').addEventListener('click',()=>go('#overview'));
main.addEventListener('click',event=>{const button=event.target.closest('[data-hint-toggle]');if(!button||!main.contains(button))return;const panel=document.getElementById(button.getAttribute('aria-controls'));if(!panel)return;panel.hidden=!panel.hidden;const expanded=!panel.hidden;button.setAttribute('aria-expanded',String(expanded));button.textContent=`${expanded?'Hide':'Reveal'} level ${button.dataset.hintToggle==='principle'?'1 · Principle':'2 · Pseudocode'}`;if(button.dataset.hintToggle==='principle'&&!expanded){const nested=panel.querySelector('[data-hint-toggle="pseudocode"]'),nestedPanel=nested&&document.getElementById(nested.getAttribute('aria-controls'));if(nested&&nestedPanel){nestedPanel.hidden=true;nested.setAttribute('aria-expanded','false');nested.textContent='Reveal level 2 · Pseudocode'}}});
window.addEventListener('hashchange',render);
document.addEventListener('keydown',event=>{if(!event.altKey||event.ctrlKey||event.metaKey)return;const match=location.hash.match(/^#lesson\/([a-z0-9-]+)$/);const index=match?lessons.findIndex(l=>l.id===match[1]):-1;if(index<0)return;if(event.key==='ArrowRight'){event.preventDefault();go(index<lessons.length-1?'#lesson/'+lessons[index+1].id:'#overview')}if(event.key==='ArrowLeft'){event.preventDefault();go(index>0?'#lesson/'+lessons[index-1].id:'#overview')}});
if(!lessons.length){main.innerHTML='<div class="error">Lesson content could not be loaded. Check that lessons.js is beside this page.</div>'}else render();
})();
