const E=(number,tex,explain,symbols,watch='')=>({number,tex,explain,symbols,watch});
window.STUDY_LESSONS=[
{
 id:'orientation',chapter:'01 · Assignment overview',section:'§1',page:1,title:'Know the whole assignment',goal:'Understand the four implementation strands, the required runs, and the evidence you will submit.',
 explain:['The assignment is an end-to-end language-modeling system. Text first becomes token IDs; a Transformer predicts the next token; an optimizer changes its weights; a training loop measures and saves progress; a decoder turns the model back into text.','The repository deliberately supplies little model code. Your implementation belongs in cs336_basics; tests/adapters.py only connects your interfaces to the staff tests. The tests themselves are the specification for observable behavior.'],
 concepts:['Implement: byte-level BPE; Transformer LM; cross-entropy and AdamW; data loading, training, and checkpoints.','Run: tokenizer training and encoding; TinyStories LM training; generation and perplexity evaluation; OpenWebText training and experiments.','Submit: typeset writeup.pdf and code.zip; leaderboard results follow a separate repository.'],formulas:[E('U0',String.raw`p_{\theta}(x_{1:T})=\prod_{t=1}^{T}p_{\theta}(x_t\mid x_{<t})`, 'An autoregressive LM assigns a sequence probability by multiplying next-token conditional probabilities.', 'T is sequence length; x_<t is the prefix before position t; θ denotes learned model parameters.', 'This describes the objective at a high level, not an assignment implementation.')],diagram:'orientation',diagramAlt:'A five-step flow from source text through BPE, token IDs, Transformer training, and generated text.',problems:[],test:'Read README, PDF §1, and tests/adapters.py; run uv run pytest to establish the starting state.',check:['Which outputs are code, which are measured results, and which are written responses?','Can you explain the direction of every arrow in the full pipeline?']
},
{
 id:'unicode',chapter:'02 · BPE tokenizer',section:'§2.1',page:3,title:'Unicode is not bytes',goal:'Separate characters, Unicode code points, byte encodings, and visible glyphs.',
 explain:['Unicode assigns an integer code point to a character. A code point does not by itself say which bytes will be stored in a file. The same abstract text can have different byte representations under UTF-8, UTF-16, and UTF-32.','Some code points are controls rather than printable marks. Inspecting a string and printing it can therefore look different. This matters when debugging token boundaries and special characters.'],concepts:['Character ≠ code point ≠ encoded byte sequence.','A visible glyph can involve multiple code points; a single code point may have no visible glyph.'],formulas:[E('U0a',String.raw`u=\operatorname{codepoint}(c),\qquad c=\operatorname{char}(u)`, 'A Unicode character and its assigned integer code point can be mapped in both directions.', 'c is one character; u is its code-point integer, not its UTF-8 byte sequence.', 'A displayed glyph is a separate rendering decision.')],diagram:'unicode',diagramAlt:'A character, its code point, its UTF-8 byte sequence, and its visual rendering shown as distinct layers.',problems:['unicode1'],test:'Written observation in PDF §2.1.',check:['What information does a code point preserve that a font rendering does not?','Why can a printed string hide a character that appears in a representation?']
},
{
 id:'utf8',chapter:'02 · BPE tokenizer',section:'§2.2',page:4,title:'Why byte-level tokenization begins with UTF-8',goal:'Reason about encoding reversibility and the size of the starting vocabulary.',
 explain:['A tokenizer must accept arbitrary text. UTF-8 converts text into bytes, so the tokenizer can start from the finite set of 256 byte values instead of a huge sparse set of Unicode code points.','A text character can occupy more than one UTF-8 byte. Token length measured in bytes is therefore different from character count. Decoding must also handle sequences that are not valid UTF-8.'],concepts:['UTF-8 is variable-length; ASCII bytes remain compact.','The byte vocabulary supports any valid UTF-8 input, but an arbitrary byte sequence need not decode cleanly.'],formulas:[E('U0b',String.raw`\operatorname{UTF8}(c)=(b_1,\ldots,b_k),\qquad 1\le k\le4`, 'One Unicode scalar value becomes one to four UTF-8 bytes.', 'Each b_i is a byte value from 0 through 255; k depends on the code point.', 'The number of bytes is not the number of visible characters.')],diagram:'utf8',diagramAlt:'One ASCII character and one multibyte character expand into different numbers of UTF-8 bytes.',problems:['unicode2'],test:'Written response in PDF §2.2.',check:['Why is a 256-byte base vocabulary sufficient to represent any UTF-8 text?','When would bytes per token and characters per token disagree?']
},
{
 id:'subword',chapter:'02 · BPE tokenizer',section:'§2.3',page:5,title:'Why subwords sit between bytes and words',goal:'Understand the tradeoff between vocabulary size, sequence length, and rare-word coverage.',
 explain:['Whole-word vocabularies make rare or unseen words difficult; byte tokens can make sequences long. Subword tokenization learns recurring byte spans and represents text with a compromise between these extremes.','The same word can split differently depending on surrounding whitespace and the training corpus. Tokenization is a learned encoding system, not a linguistic parser.'],concepts:['Larger vocabularies often shorten token sequences but enlarge embedding and output matrices.','The tokenizer is part of the model’s measurement system: changing it also changes token-level loss comparisons.'],formulas:[E('U0c',String.raw`N_{\mathrm{tokens}}=\frac{N_{\mathrm{bytes}}}{r_{\mathrm{bytes/token}}}`, 'This relationship makes the sequence-length side of the vocabulary tradeoff explicit.', 'N_bytes and N_tokens describe the same text; r is its measured bytes-per-token ratio.', 'Increasing r can shorten sequences but usually requires a larger vocabulary.')],diagram:'subword',diagramAlt:'A continuum from byte tokens to subword tokens to whole-word tokens with contrasting sequence and vocabulary sizes.',problems:[],test:'Read PDF §2.3 before BPE training.',check:['What changes if vocabulary size grows while the text stays fixed?','Why can two tokenizers produce different token-level losses on the same text?']
},
{
 id:'bpe-train',chapter:'02 · BPE tokenizer',section:'§2.4',page:5,title:'How BPE learns a vocabulary',goal:'Understand pre-token boundaries, pair counts, merge order, and special-token boundaries.',
 explain:['Training begins with individual bytes. Within each pre-token, frequently adjacent byte units become candidates for merging. Each chosen merge adds a new vocabulary item, and its position in the merge list matters later during encoding.','Pre-tokenization is a hard boundary: counts should not connect neighboring pre-tokens. Special tokens also split the training text into boundaries and are excluded from ordinary pair statistics. The handout discusses parallelizing pre-tokenization and maintaining pair counts efficiently.'],concepts:['The final vocabulary includes base bytes, merged units, and special tokens.','A merge list is ordered history, not just an unordered collection of byte pairs.','Tie handling and special-token treatment affect reproducibility and tests.'],formulas:[E('U1',String.raw`|V_{\mathrm{final}}|=256+|S|+N_{\mathrm{merges}}`, 'A bookkeeping identity for the vocabulary budget; stop when the requested total size is reached.', 'V is the vocabulary, S is the special-token set, and N_merges counts learned entries.', 'The exact count assumes no duplicate special-token entries.')],diagram:'bpe-train',diagramAlt:'Adjacent byte pairs within separate pre-tokens accumulate counts, and the most frequent pair becomes a merged vocabulary item.',problems:['train_bpe'],test:'uv run pytest tests/test_train_bpe.py',check:['Why is the merge history ordered?','Which boundaries must pair counts never cross?','What must the requested vocabulary size include?']
},
{
 id:'bpe-runs',chapter:'02 · BPE tokenizer',section:'§2.5',page:8,title:'Train and compare two vocabularies',goal:'Interpret the TinyStories and OpenWebText tokenizer experiments.',
 explain:['The handout asks for a 10K TinyStories tokenizer and a 32K OpenWebText tokenizer. These corpora differ in style and diversity, so learned long tokens and merge frequencies should differ. Measure training time and memory rather than assuming the algorithm is fast enough.','The longest token is a diagnostic, not automatically an error. Inspect its bytes and its corpus context before judging whether it is plausible. Profile pre-tokenization separately from repeated merge updates.'],concepts:['TinyStories uses <|endoftext|> as a special token.','Keep training and validation data separate when later evaluating the LM.','Compare learned vocabularies qualitatively and quantitatively.'],formulas:[E('U2',String.raw`r_{\mathrm{compression}}=\frac{\text{input UTF-8 bytes}}{\text{output token IDs}}`, 'Compression ratio expresses how much original text each token represents on average.', 'The numerator and denominator must describe the same sampled documents.', 'A higher ratio does not by itself prove better downstream LM quality.')],diagram:'bpe-runs',diagramAlt:'Two corpora lead to distinct tokenizer vocabularies, with bars representing different byte-per-token ratios.',problems:['train_bpe_tinystories','train_bpe_expts_owt'],test:'Record time, peak memory, longest token, and comparison required by PDF §2.5.',check:['What does a longest token reveal about the corpus?','What can a profiler tell you that total runtime cannot?']
},
{
 id:'tokenizer',chapter:'02 · BPE tokenizer',section:'§2.6–2.6.2',page:10,title:'Encode, stream, and decode',goal:'Trace text to token IDs and back without losing boundary semantics.',
 explain:['Encoding repeats pre-tokenization, applies learned merges in their training order within each pre-token, and maps resulting byte units to IDs. Special tokens must be recognized as indivisible spans.','Decoding maps IDs to bytes, concatenates bytes, then decodes UTF-8. A streaming encoder must preserve the same tokenization as whole-text encoding even when input arrives in chunks; chunk boundaries are an I/O detail, not token boundaries.'],concepts:['Round-trip behavior, Unicode edge cases, and overlapping special tokens are essential checks.','An arbitrary ID sequence may decode to malformed UTF-8; the handout specifies replacement behavior.','Memory usage should be bounded for a large iterable.'],formulas:[E('U0d',String.raw`\operatorname{decode}(\operatorname{encode}(s))=s`, 'A valid text string should survive an encode–decode round trip.', 's is the original text; encoding returns token IDs and decoding reconstructs text.', 'This invariant does not imply that arbitrary ID sequences form valid UTF-8.')],diagram:'tokenizer',diagramAlt:'An encoder and decoder loop showing pre-tokens, ordered merges, token IDs, byte concatenation, and decoded text.',problems:['tokenizer'],test:'uv run pytest tests/test_tokenizer.py',check:['Why can decoding need replacement characters even if normal encoding starts from valid text?','How would you tell if a chunk boundary changed tokenization?']
},
{
 id:'tokenizer-exp',chapter:'02 · BPE tokenizer',section:'§2.7',page:12,title:'Measure the tokenizer as a system',goal:'Interpret compression, throughput, cross-corpus transfer, and serialized token IDs.',
 explain:['The handout asks you to sample documents from both corpora, compare both trained tokenizers, and estimate tokenization throughput. Record the measurement setup because throughput depends on implementation, file size, and machine.','The encoded train and validation arrays become the LM’s input. Their integer dtype must represent every token ID; choosing a larger dtype wastes storage and bandwidth, while choosing a smaller one corrupts IDs.'],concepts:['Use bytes/token for a corpus-specific compression comparison.','Cross-corpus tokenization is a useful distribution-shift test.','Keep provenance of the tokenizer used for each array.'],formulas:[E('U3',String.raw`\text{throughput}=\frac{\text{bytes processed}}{\text{elapsed seconds}}`, 'Throughput is a rate, so timing must cover the same work as the byte count.', 'Report bytes and seconds explicitly, then extrapolate only with stated assumptions.', 'Disk I/O and warm caches can change the estimate.')],diagram:'tokenizer-exp',diagramAlt:'A measurement dashboard diagram for bytes per token, processing rate, and token ID storage.',problems:['tokenizer_experiments'],test:'Written measurements and serialized train/validation arrays in PDF §2.7.',check:['Why is token ID dtype a correctness decision?','How would you make a tokenizer throughput estimate reproducible?']
},
{
 id:'lm-pipeline',chapter:'03 · Transformer architecture',section:'§3.1',page:13,title:'The decoder-only LM at a glance',goal:'Follow shapes from token IDs through embeddings and blocks to next-token logits.',
 explain:['An input of shape (batch, sequence) becomes an embedding tensor of shape (batch, sequence, d_model). Each Transformer block preserves this shape. Final normalization and a vocabulary projection produce logits of shape (batch, sequence, vocab_size).','Every position predicts the next token, but the causal structure forbids using later tokens at that position. During generation, only the last available position’s prediction is sampled for the next step.'],concepts:['Logits are unnormalized scores, not probabilities.','Residual connections preserve an uninterrupted path through the stack.','The output vocabulary dimension is set by the tokenizer.'],formulas:[E('U4',String.raw`(B,T)\;\longrightarrow\;(B,T,d_{\mathrm{model}})\;\longrightarrow\;(B,T,|V|)`, 'This shape flow is the model’s contract from IDs to logits.', 'B is batch size, T is sequence length, d_model is hidden width, and |V| is vocabulary size.', 'The sequence axis is retained so one forward pass predicts every next-token target.')],diagram:'lm-pipeline',diagramAlt:'Token IDs flow into embeddings, repeated Transformer blocks, final normalization, and vocabulary logits.',problems:[],test:'Use PDF Figures 1–2 and explain tensor shapes without looking at implementation.',check:['What is the shape after a Transformer block?','Why does training use logits at every position but generation use the last position?']
},
{
 id:'batching',chapter:'03 · Transformer architecture',section:'§3.2–3.2.1',page:14,title:'Batch axes and matrix notation',goal:'Translate column-vector equations into batched tensor operations.',
 explain:['The handout uses column vectors in mathematics but typical PyTorch tensors place the feature axis last. Thus the same linear map can be written differently depending on notation. Labeling axes with einsum can make intended contractions clearer.','Batch-like axes should be carried through operations unchanged. Attention later adds sequence and head axes, so shape discipline prevents many bugs.'],concepts:['An ellipsis can stand for any number of leading batch-like dimensions.','The matrix W stores out_features × in_features in either convention.','Memory layout and mathematical orientation are related but not identical concepts.'],formulas:[E(1,String.raw`y=xW^{\top}`, 'Row-vector notation puts the feature axis last, matching a batched tensor with trailing input features.', 'x has shape (1,d_in); W has shape (d_out,d_in); y has shape (1,d_out).', 'Transpose placement changes with notation, not with the learned transformation.'),E(2,String.raw`y=Wx`, 'Column-vector notation is the conventional linear algebra form used by most later equations.', 'x has shape (d_in,1); W has shape (d_out,d_in); y has shape (d_out,1).', 'When translating to PyTorch, track axes instead of copying matrix symbols literally.')],diagram:'batching',diagramAlt:'Row-vector and column-vector matrix multiplication layouts shown side by side with matching dimensions.',problems:[],test:'Check shapes for batch, sequence, and feature axes before each model component.',check:['How can equations (1) and (2) describe the same learned map?','What axis convention will you use when inspecting a test failure?']
},
{
 id:'linear-embedding',chapter:'03 · Transformer architecture',section:'§3.3–3.3.3',page:17,title:'Linear maps and token embeddings',goal:'Understand parameter shapes and initialization without relying on built-in layers.',
 explain:['A bias-free Linear map transforms the final feature axis. An embedding table is different: it selects a row indexed by a token ID, returning a vector rather than performing a one-hot matrix multiplication in practice.','The handout gives approximate truncated-normal initializations and a unit gain for RMSNorm. Initialization affects activation scale and training behavior, so match the specified shapes and distributions.'],concepts:['Linear W has shape (d_out,d_in); an embedding table has shape (vocab_size,d_model).','The assignment forbids using the corresponding torch.nn and torch.nn.functional implementations for these components.','The stored parameter orientation must match the test adapter contract.'],formulas:[E(3,String.raw`y=Wx`, 'This is the assignment’s bias-free Linear transformation.', 'For a single column vector, W maps d_in features to d_out features; in a batched implementation, only the last axis changes.', 'The absence of a bias is intentional.')],diagram:'linear-embedding',diagramAlt:'A token ID selects an embedding row, while a separate weight matrix transforms feature vectors.',problems:['linear','embedding'],test:'uv run pytest -k "test_linear or test_embedding"',check:['Why is an embedding lookup conceptually similar to selecting a one-hot projection?','Which dimension changes after a Linear map?']
},
{
 id:'rmsnorm',chapter:'03 · Transformer architecture',section:'§3.4.1',page:19,title:'RMSNorm and activation scale',goal:'Interpret the normalization axis, learnable gain, and numerical stability.',
 explain:['RMSNorm measures the root mean square magnitude of a feature vector and divides each feature by that common scale before applying a learned gain. Unlike centering-based normalization, it does not subtract the mean.','The handout notes that squaring low-precision values can overflow. Think about accumulation dtype and the requested output dtype separately.'],concepts:['Normalize over d_model, independently for every batch and sequence position.','The gain g has one learnable value per model feature.','ε prevents division by a near-zero denominator.'],formulas:[E(4,String.raw`\operatorname{RMSNorm}(a_i)=\frac{a_i}{\operatorname{RMS}(a)}g_i`, 'Each feature is scaled by a shared vector magnitude and then by its own learned gain.', String.raw`a\in\mathbb{R}^{d_{\mathrm{model}}};\quad\operatorname{RMS}(a)=\sqrt{\frac{1}{d_{\mathrm{model}}}\sum_j a_j^2+\epsilon}.`, 'Keep the normalization axis and numerical precision explicit.')],diagram:'rmsnorm',diagramAlt:'A feature vector is rescaled by a shared RMS magnitude and per-feature gain.',problems:['rmsnorm'],test:'uv run pytest -k test_rmsnorm',check:['Which axis contributes to the RMS denominator?','Why does ε matter even if most vectors have nonzero magnitude?']
},
{
 id:'swiglu',chapter:'03 · Transformer architecture',section:'§3.4.2',page:21,title:'SiLU, gates, and the feed-forward block',goal:'Read the activation and gating equations and identify the dimensions of each branch.',
 explain:['A position-wise feed-forward network acts on each token independently, while attention is the operation that mixes information across positions. SwiGLU has two parallel projections: one passes through SiLU and gates the other by elementwise multiplication.','The inner width d_ff determines both capacity and cost. The handout’s comparison to a plain SiLU network later changes width to keep parameter counts comparable.'],concepts:['SiLU is smooth around zero.','The gate multiplies aligned d_ff-dimensional vectors.','The final projection returns to d_model, preserving the residual-stream width.'],formulas:[E(5,String.raw`\operatorname{SiLU}(x)=x\sigma(x)=\frac{x}{1+e^{-x}}`, 'SiLU multiplies the input by a sigmoid gate.', 'x may be scalar or a tensor; σ acts elementwise.', 'The output can be slightly negative for negative x.'),E(6,String.raw`\operatorname{GLU}(x,W_1,W_2)=\sigma(W_1x)\odot W_2x`, 'A gated linear unit multiplies two projected branches elementwise.', '⊙ means elementwise product; the branches must have matching shapes.', 'The handout’s later SwiGLU equation uses a different three-matrix naming pattern.'),E(7,String.raw`\operatorname{FFN}(x)=W_2\bigl(\operatorname{SiLU}(W_1x)\odot W_3x\bigr)`, 'The SwiGLU FFN combines a SiLU branch with a linear branch, then projects back to model width.', 'W₁ and W₃ map d_model to d_ff; W₂ maps d_ff back to d_model.', 'Check that multiplication is elementwise before the output projection.')],diagram:'swiglu',diagramAlt:'Two parallel feed-forward branches combine at an elementwise gate before an output projection.',problems:['positionwise_feedforward'],test:'uv run pytest -k "test_silu or test_swiglu"',check:['Which part of a Transformer mixes token positions?','Why must the two gated branches have identical inner widths?']
},
{
 id:'rope',chapter:'03 · Transformer architecture',section:'§3.4.3',page:22,title:'RoPE as position-dependent rotation',goal:'See how paired query and key features encode relative position.',
 explain:['RoPE rotates pairs of query and key features by an angle based on token position and feature-pair frequency. The large matrix in the handout is block diagonal: each two-dimensional pair rotates independently.','The useful intuition is geometric. Rotating two vectors by position-dependent angles makes their dot product sensitive to relative position. The trigonometric values are fixed, not learned model weights.'],concepts:['Apply the positional rotation to query and key vectors, not arbitrary value vectors.','The head feature width is paired into two-dimensional planes.','A table of sin/cos values can be reused across batches and layers.'],formulas:[E(8,String.raw`R_k^{(i)}=\begin{pmatrix}\cos\theta_{i,k}&-\sin\theta_{i,k}\\\sin\theta_{i,k}&\cos\theta_{i,k}\end{pmatrix}`, 'Each 2×2 block rotates one adjacent pair of features at token position i.', String.raw`\theta_{i,k}=i\,\Theta^{-(2k-2)/d};\quad k\in\{1,\ldots,d/2\}.`, 'The exact indexing convention in the PDF is one-based; preserve the same frequencies when translating conventions.'),E(9,String.raw`R^{(i)}=\operatorname{diag}\bigl(R_1^{(i)},R_2^{(i)},\ldots,R_{d/2}^{(i)}\bigr)`, 'The full d×d rotation is a block-diagonal collection of independent 2D rotations.', 'd is the per-head query/key feature dimension and must be even.', 'This notation explains the map; it does not require constructing a dense matrix.')],diagram:'rope',diagramAlt:'Two feature-pair vectors rotate through different angles at two token positions.',problems:['rope'],test:'uv run pytest -k test_rope',check:['Why are features handled in pairs?','Which quantities are fixed by position, and which are learned?']
},
{
 id:'attention',chapter:'03 · Transformer architecture',section:'§3.4.4',page:23,title:'Softmax, attention scores, and masks',goal:'Track the score matrix from QKᵀ through scaling, masking, normalization, and V mixing.',
 explain:['The attention score for query i and key j is a dot product. Scores are divided by the square root of key width, masked when information flow is forbidden, and normalized across the key axis. The resulting weights mix value vectors.','A boolean mask marks allowed query–key pairs. The mask must affect scores before softmax; setting a probability to zero afterward would disturb normalization. Subtracting the largest logit makes exponentiation stable without changing the distribution.'],concepts:['Q: n×d_k, K: m×d_k, V: m×d_v; output: n×d_v, with optional leading batch axes.','A True mask entry means attention is allowed in this handout.','A causal mask prevents a position from seeing future positions.'],formulas:[E(10,String.raw`\operatorname{softmax}(v)_i=\frac{e^{v_i}}{\sum_{j=1}^{n}e^{v_j}}`, 'Softmax turns a score vector into nonnegative weights that sum to one.', 'The index j ranges over the normalized axis; for attention this is the key axis.', 'Subtracting max(v) from every score leaves the ratio unchanged and avoids overflow.'),E(11,String.raw`\operatorname{Attention}(Q,K,V)=\operatorname{softmax}\!\left(\frac{QK^{\top}}{\sqrt{d_k}}\right)V`, 'Queries compare with keys; the resulting probability matrix forms a weighted combination of values.', 'QKᵀ has shape n×m; multiplying by V gives n×d_v.', 'Apply any mask to the score matrix before softmax.')],diagram:'attention',diagramAlt:'A small causal attention matrix shows allowed and blocked query–key cells before values are mixed.',problems:['softmax','scaled_dot_product_attention'],test:'uv run pytest -k "test_softmax_matches_pytorch or test_scaled_dot_product_attention or test_4d_scaled_dot_product_attention"',check:['Along which dimension must each attention row sum to one?','Why is masking after softmax incorrect?']
},
{
 id:'mha',chapter:'03 · Transformer architecture',section:'§3.4.5',page:25,title:'Multiple attention heads',goal:'Understand head slicing, parallel subspaces, projection shapes, and causal self-attention.',
 explain:['Multi-head attention performs separate attention operations over slices of projected query, key, and value features. The head outputs are concatenated and mapped back to model width by an output projection.','Self-attention uses the same input sequence to form Q, K, and V. RoPE and causal masking must fit the head and sequence axes without changing the basic attention equation.'],concepts:['Heads run over distinct learned projection slices.','The number of heads times per-head width determines concatenated width.','Check batch, head, query-position, key-position, and feature axes separately.'],formulas:[E(12,String.raw`\operatorname{MultiHead}(Q,K,V)=\operatorname{Concat}(\mathrm{head}_1,\ldots,\mathrm{head}_h)`, 'Concatenate independent head outputs along their feature dimension.', 'h is the number of heads; each head returns value-width features.', 'Concatenation does not combine sequence positions.'),E(13,String.raw`\mathrm{head}_i=\operatorname{Attention}(Q_i,K_i,V_i)`, 'Each head applies the same attention operation to its own projection slice.', 'Subscript i identifies a head, not a token position.', 'Every head still obeys the same causal restriction.'),E(14,String.raw`\operatorname{MHSA}(x)=W_O\operatorname{MultiHead}(W_Qx,W_Kx,W_Vx)`, 'Three learned projections create Q, K, and V; a fourth projection recombines heads.', 'x has model width; W_Q, W_K, W_V project to h×head width; W_O returns to d_model.', 'Track column-vector notation against actual tensor layout.')],diagram:'mha',diagramAlt:'Input features split into multiple projected heads, attend in parallel, concatenate, and return through an output projection.',problems:['multihead_self_attention'],test:'uv run pytest -k "test_multihead_self_attention or test_multihead_self_attention_with_rope"',check:['Which axis is split into heads?','How does output projection restore the residual-stream width?']
},
{
 id:'full-lm',chapter:'03 · Transformer architecture',section:'§3.5',page:26,title:'Assemble the full LM and count its cost',goal:'Connect pre-norm blocks to the final vocabulary projection and reason about parameters and FLOPs.',
 explain:['A pre-norm block normalizes its input before attention, adds an attention residual, then normalizes the intermediate stream before its FFN and adds another residual. Stacking blocks preserves the hidden width.','Resource accounting starts with shapes. For each learned matrix, multiply its dimensions for parameter count; for each matrix multiplication, use the general 2mnp FLOP estimate. Sequence length changes the quadratic attention score term especially strongly.'],concepts:['Embedding, per-block projections, normalization gains, and LM head all contribute parameters.','Separate parameter memory from optimizer state and activation memory.','Use the handout’s model sizes for your own written accounting rather than copying results.'],formulas:[E(15,String.raw`y=x+\operatorname{MHSA}(\operatorname{RMSNorm}(x))`, 'The first half of a pre-norm block adds the attention transformation back to the unchanged residual stream.', 'x and y both have shape (B,T,d_model).', 'The FFN half applies the analogous normalize–transform–add pattern.'),E('U5',String.raw`\operatorname{FLOPs}(A_{m\times n}B_{n\times p})\approx2mnp`, 'This general matrix-multiply estimate is the basis of the handout’s resource-accounting questions.', 'm, n, and p are matrix dimensions; multiply counts are approximately paired with additions.', 'Do not substitute the assignment’s requested model configurations until solving the written problem yourself.')],diagram:'full-lm',diagramAlt:'A pre-norm residual block repeated in a stack leads to final normalization and logits; side labels show parameter and FLOP accounting.',problems:['transformer_block','transformer_lm','transformer_accounting'],test:'uv run pytest tests/test_model.py; complete the written resource-accounting prompts.',check:['Why do both residual additions require matching shapes?','Which quantities grow with sequence length, and which depend only on model width?']
},
{
 id:'cross-entropy',chapter:'04 · Training mathematics',section:'§4.1',page:28,title:'Cross-entropy and perplexity',goal:'Connect next-token probabilities, stable negative log likelihood, and evaluation perplexity.',
 explain:['At each position, the model emits a logit for every vocabulary item. The probability assigned to the actual next token determines that position’s loss. Cross-entropy averages negative log probabilities across positions and training sequences.','Perplexity exponentiates average token loss. Its value depends on tokenization and the evaluation set, so only compare values when those choices match. A stable computation avoids directly taking the log of a tiny softmax probability.'],concepts:['Targets are shifted by one token relative to inputs.','The vocabulary axis is last; other axes are batch-like and reduced in the average.','The log-sum-exp viewpoint explains numerical stability.'],formulas:[E(16,String.raw`\ell(\theta;D)=\frac{1}{|D|m}\sum_{x\in D}\sum_{i=1}^{m}-\log p_{\theta}(x_{i+1}\mid x_{1:i})`, 'Average the surprise of the true next token over examples and predicted positions.', 'D is the set of sequences, m is predictions per sequence, and θ denotes model parameters.', 'The denominator changes if examples have unequal valid lengths; the assignment uses fixed-length sequences.'),E(17,String.raw`p(x_{i+1}\mid x_{1:i})=\frac{e^{o_i[x_{i+1}]}}{\sum_{a=1}^{|V|}e^{o_i[a]}}`, 'The true token’s logit is normalized against every vocabulary logit at position i.', 'o_i has |V| entries; x_{i+1} is the target token ID.', 'Shift logits before exponentiation to prevent overflow.'),E(18,String.raw`\operatorname{PPL}=\exp\!\left(\frac{1}{m}\sum_{i=1}^{m}\ell_i\right)`, 'Perplexity is the exponential of mean per-token cross-entropy.', 'ℓ_i is the negative log probability of the true token at position i.', 'PPL is tokenization-dependent; report the tokenizer with the metric.')],diagram:'cross-entropy',diagramAlt:'Three next-token predictions contribute negative log probabilities that are averaged and exponentiated to yield perplexity.',problems:['cross_entropy'],test:'uv run pytest -k test_cross_entropy',check:['Which logit enters the numerator of equation (17)?','Why does evaluating with a different tokenizer make perplexity hard to compare?']
},
{
 id:'sgd',chapter:'04 · Training mathematics',section:'§4.2–4.2.1',page:29,title:'What an optimizer step means',goal:'Read SGD as movement opposite a batch gradient and observe learning-rate behavior.',
 explain:['An optimizer updates parameters to reduce loss estimated on a sampled batch. The gradient gives a local direction; the learning rate controls step size. Too-small steps learn slowly; sufficiently large ones can be unstable.','The handout’s toy SGD example also changes the step size over time. Treat that example as an opportunity to inspect loss behavior, not as the optimizer used in the final LM.'],concepts:['A gradient is computed from the current parameter state and batch.','Loss curves are evidence; do not assume a learning rate is good because it is numerically small.','The Optimizer base class manages parameter groups and state.'],formulas:[E(19,String.raw`\theta_{t+1}\leftarrow\theta_t-\alpha_t\nabla L(\theta_t;B_t)`, 'SGD moves parameters opposite the loss gradient from batch B_t.', 'θ_t is the parameter state; α_t is learning rate; ∇L has the same shape as θ.', 'The quality of this local direction depends on batch and current position.'),E(20,String.raw`\theta_{t+1}=\theta_t-\frac{\alpha}{\sqrt{t+1}}\nabla L(\theta_t;B_t)`, 'The toy example reduces its effective learning rate as t grows.', 'α is the initial scale; t starts at zero here so the first denominator is one.', 'This decay is pedagogical and distinct from the later cosine schedule.')],diagram:'sgd',diagramAlt:'Gradient arrows of different learning-rate lengths move across a smooth loss landscape, including an overshoot.',problems:['learning_rate_tuning'],test:'Run the handout’s toy experiment and describe the observed loss behavior.',check:['What is held fixed when comparing learning rates in the toy experiment?','How can a large step increase loss even if the gradient points downhill locally?']
},
{
 id:'adamw',chapter:'04 · Training mathematics',section:'§4.3',page:31,title:'AdamW tracks two memories of gradients',goal:'Understand first and second moments, bias correction, and decoupled weight decay.',
 explain:['AdamW maintains a moving average of gradients and of squared gradients for each parameter. The first estimates direction; the second scales updates by recent magnitude. Bias adjustment matters early because both averages start at zero.','Weight decay pulls parameters toward zero separately from the gradient-adjusted update. This distinction is the “W” in AdamW and affects how regularization interacts with adaptive scaling.'],concepts:['m and v have the same shape as parameters and add memory cost.','β₁ and β₂ determine how much history each moment retains.','ε protects a small denominator; λ sets weight-decay strength.'],formulas:[E('U6',String.raw`m_t=\beta_1m_{t-1}+(1-\beta_1)g_t`, 'The first moment is an exponential moving average of gradients.', 'g_t is the current gradient; β₁ is the retention factor.', 'The initial zero state makes early estimates biased toward zero.'),E('U7',String.raw`v_t=\beta_2v_{t-1}+(1-\beta_2)g_t^2`, 'The second moment tracks squared-gradient magnitude elementwise.', 'β₂ controls its timescale; v_t has parameter shape.', 'Square and division are elementwise in the optimizer description.'),E('U8',String.raw`\alpha_t=\alpha\frac{\sqrt{1-\beta_2^t}}{1-\beta_1^t}`, 'This adjusted step size compensates for moments that began at zero.', 't starts at one in the handout’s AdamW algorithm.', 'The formula accompanies separate weight decay and moment-based update; it is not the full update alone.')],diagram:'adamw',diagramAlt:'A current gradient feeds two moving-average state boxes before an adaptive update, with weight decay shown as a separate path.',problems:['adamw','adamw_accounting'],test:'uv run pytest -k test_adamw; answer memory and runtime accounting questions.',check:['Why are two extra parameter-shaped states needed?','What makes weight decay “decoupled” from the gradient path?']
},
{
 id:'schedule',chapter:'04 · Training mathematics',section:'§4.4',page:33,title:'Warm up, decay, then hold',goal:'Interpret the three intervals of the cosine learning-rate schedule.',
 explain:['A warmup raises the learning rate from a small starting value. A cosine phase then smoothly lowers it from the maximum to a minimum. After the decay endpoint, the schedule stays at the minimum.','Check the values at the boundaries, not only in the middle. A schedule that jumps unexpectedly at warmup or decay endpoints can undermine experiments even when the model math is correct.'],concepts:['T_w is the warmup endpoint; T_c is the cosine-decay endpoint.','α_max and α_min are rates, not parameter magnitudes.','For a shortened low-resource run, the decay endpoint should match the actual run length.'],formulas:[E('U9',String.raw`\alpha_t=\begin{cases}\frac{t}{T_w}\alpha_{\max},&t<T_w\\[2pt]\alpha_{\min}+\frac{1+\cos\!\left(\pi\frac{t-T_w}{T_c-T_w}\right)}{2}(\alpha_{\max}-\alpha_{\min}),&T_w\le t\le T_c\\[2pt]\alpha_{\min},&t>T_c\end{cases}`, 'The schedule is piecewise: linear warmup, cosine anneal, constant floor.', 't is current step; T_w and T_c delimit phases; α_max and α_min are peak and floor.', 'Inspect t = 0, T_w, T_c, and one step beyond T_c.')],diagram:'schedule',diagramAlt:'A learning-rate curve rises linearly, falls along a cosine arc, and remains flat at the minimum.',problems:['learning_rate_schedule'],test:'uv run pytest -k test_get_lr_cosine_schedule',check:['What are the expected values exactly at T_w and T_c?','Why can a schedule designed for a long run mislead a short experiment?']
},
{
 id:'clipping',chapter:'04 · Training mathematics',section:'§4.5',page:34,title:'Gradient clipping bounds the whole update',goal:'Distinguish a global norm cap from clipping each gradient element independently.',
 explain:['Training can encounter a batch with a very large gradient. Global-norm clipping considers all parameter gradients together and rescales them only when their combined L2 norm exceeds a threshold.','The direction of the concatenated gradient is retained under uniform rescaling. The handout specifies a small ε for numerical safety in the scale factor.'],concepts:['Parameters without a gradient do not contribute to the norm.','The gradient is modified before the optimizer step.','Clipping controls extreme updates but does not fix an incorrect loss or mask.'],formulas:[E('U10',String.raw`\|g\|_2=\sqrt{\sum_{p}\sum_j g_{p,j}^2},\qquad g'_{p,j}=g_{p,j}\min\!\left(1,\frac{M}{\|g\|_2+\epsilon}\right)`, 'The same factor applies to every gradient element if the global norm exceeds M.', 'p ranges over parameters; j over each parameter’s entries; M is the maximum norm.', 'For a norm already below M, the factor is one and gradients remain unchanged.')],diagram:'clipping',diagramAlt:'A long gradient vector is shortened to a norm boundary while preserving its direction.',problems:['gradient_clipping'],test:'uv run pytest -k test_gradient_clipping',check:['Why does global clipping preserve direction?','At what point in the training step does clipping belong?']
},
{
 id:'data',chapter:'05 · Training loop',section:'§5.1',page:34,title:'Sample next-token training pairs',goal:'See how a continuous token array yields aligned inputs and targets.',
 explain:['The encoded corpus is a long sequence of token IDs with document delimiters. A training sample takes a context window and pairs it with the same window shifted one token forward. Random starts produce fixed-length batches without padding.','Memory mapping can expose a large token array without eagerly reading all its bytes into RAM. The dtype and maximum ID must still match the tokenizer.'],concepts:['Inputs and targets both have shape (batch_size, context_length).','The target at each position is exactly one token later than the input.','Moving only sampled batches to the requested device avoids loading the entire corpus there.'],formulas:[E('U11',String.raw`X_b=x_{s_b:s_b+T},\qquad Y_b=x_{s_b+1:s_b+T+1}`, 'A start index s_b defines one context window and its one-step-shifted targets.', 'b is batch item; T is context length; x is the encoded corpus.', 'The final legal start must leave room for T+1 tokens.')],diagram:'data',diagramAlt:'A token stream yields an input window and a target window shifted one position to the right.',problems:['data_loading'],test:'uv run pytest -k test_get_batch',check:['Why must the sampled slice contain T+1 original tokens?','What would a target alignment bug look like in a tiny example?']
},
{
 id:'checkpoint',chapter:'05 · Training loop',section:'§5.2',page:35,title:'A checkpoint is more than weights',goal:'Identify every state needed to resume a run faithfully.',
 explain:['Model weights alone let you sample from a saved model, but a resumed AdamW run also needs optimizer moments and the current iteration. The iteration determines the next learning rate and where to place new logs on the curve.','The handout tests round-trip save and load through model and optimizer state dictionaries. Consider a checkpoint a snapshot of the training process, not just a model file.'],concepts:['Model, optimizer, and iteration are the minimum stated payload.','A resumed run should continue with the intended schedule phase.','Large checkpoint files should not accidentally enter the submission ZIP.'],formulas:[E('U0e',String.raw`C_t=(\theta_t,\;S_{\mathrm{optimizer},t},\;t)`, 'A restartable checkpoint includes the model, optimizer state, and training position.', 'θ_t is the model state; S_optimizer,t includes AdamW moments; t identifies the iteration.', 'Saving only θ_t is sufficient for inference but not a faithful optimizer resume.')],diagram:'checkpoint',diagramAlt:'A training process saves model weights, optimizer moments, and step count into one checkpoint that can restore the run.',problems:['checkpointing'],test:'uv run pytest -k test_checkpointing',check:['What goes wrong if optimizer state is omitted on resume?','Why is iteration number necessary even when parameters are restored?']
},
{
 id:'train-loop',chapter:'05 · Training loop',section:'§5.3',page:36,title:'Close the training loop',goal:'Put token data, model, loss, optimizer, validation, and checkpoints into one observable run.',
 explain:['A training run repeatedly samples a batch, obtains next-token logits, computes loss, derives gradients, applies any clipping and scheduled learning rate, then updates parameters. Periodic validation measures generalization without changing weights.','The handout asks for configurable hyperparameters, memory-efficient data loading, checkpoints, and performance logging. Before expensive runs, the recommended sanity check is overfitting a single minibatch.'],concepts:['Training loss and validation loss answer different questions.','Log both step number and wall-clock time so later experiments are comparable.','A short end-to-end run tests interfaces that isolated unit tests cannot.'],formulas:[E('U12',String.raw`\text{tokens processed}=B\times T\times N_{\mathrm{steps}}`, 'This budget compares runs more fairly than step count alone when batch size or context length changes.', 'B is batch size; T is context length; N_steps is optimizer updates.', 'Wall-clock time and throughput still matter for a fixed-compute comparison.')],diagram:'train-loop',diagramAlt:'A closed loop from batch sampling to logits, loss, gradients, optimizer update, validation, and checkpoint logging.',problems:['training_together'],test:'Run uv run pytest; then a short train/validate/resume smoke test.',check:['Which measurements should happen with model weights frozen?','Why is overfitting one batch a useful correctness probe?']
},
{
 id:'generation',chapter:'06 · Generating text',section:'§6',page:37,title:'Generate one token at a time',goal:'Read next-token sampling, temperature, nucleus filtering, and stopping criteria.',
 explain:['Given a prompt, the LM produces logits at every supplied position, but the last position gives the next-token distribution. Sample one token, append it to the prompt, and repeat until an end token or chosen length limit.','Temperature changes distribution sharpness. Top-p keeps a smallest high-probability set with cumulative mass at least p and renormalizes it. These are inference choices; they do not repair a poorly trained model.'],concepts:['Only the last logit vector predicts the next unseen token.','Low temperature sharpens; higher temperature spreads probability.','Sampling behavior should be reported with its settings and seed.'],formulas:[E(21,String.raw`P(x_{t+1}=i\mid x_{1:t})=\frac{e^{v_i}}{\sum_j e^{v_j}}`, 'The next token is sampled from the softmax of final-position logits.', 'i ranges over vocabulary IDs; v is the final-position logit vector.', 'Use normalized probabilities, not raw logits, for sampling.'),E(22,String.raw`v=\operatorname{TransformerLM}(x_{1:t})_t\in\mathbb{R}^{|V|}`, 'Select the model output at the final prompt position.', '|V| is vocabulary size; subscript t identifies the last supplied position.', 'Later generated tokens become part of the next model input.'),E(23,String.raw`\operatorname{softmax}(v,\tau)_i=\frac{e^{v_i/\tau}}{\sum_j e^{v_j/\tau}}`, 'Temperature rescales logits before normalization.', 'τ>0 is temperature; τ below one usually concentrates probability.', 'At very small τ, numerical and limiting behavior deserve care.'),E(24,String.raw`P(i\mid q)=\begin{cases}\dfrac{q_i}{\sum_{j\in V(p)}q_j},&i\in V(p)\\[5pt]0,&i\notin V(p)\end{cases}`, 'Top-p sampling keeps the smallest set V(p) whose cumulative q-probability reaches p, then renormalizes.', 'q is the temperature-scaled distribution; p is a cumulative probability threshold.', 'The retained set depends on sorting probabilities, not token IDs.')],diagram:'generation',diagramAlt:'A prompt produces last-position logits, then temperature and top-p filtering select a new token that feeds back into the prompt.',problems:['decoding'],test:'Inspect short generated samples with fixed prompt, seed, temperature, top-p, and maximum length.',check:['Which model output position is sampled?','How do temperature and top-p alter different parts of the distribution?']
},
{
 id:'experiment-log',chapter:'07 · Experiments',section:'§7.1',page:38,title:'Make every run interpretable',goal:'Record the configuration, budget, metrics, and curves needed to explain experimental results.',
 explain:['Experiments are valuable only if the setup can be reconstructed. Record model and tokenizer versions, dataset split, seed, optimizer settings, step count, tokens processed, wall-clock time, validation loss, and checkpoints.','A curve against steps shows optimization dynamics; a curve against time shows practical efficiency. They can tell different stories when batch size or model cost changes.'],concepts:['Validation should use the same tokenization policy as training.','Preserve raw logs as well as rendered curves.','State a hypothesis before changing a hyperparameter or architecture.'],formulas:[E('U0f',String.raw`\text{throughput}=\frac{B\,T\,N_{\mathrm{steps}}}{\text{wall-clock seconds}}`, 'Token throughput gives a time-based efficiency measure for a training run.', 'B is batch size, T is context length, and N_steps is update count.', 'Specify whether setup, validation, and checkpoint time are included.')],diagram:'experiment-log',diagramAlt:'Two loss curves from the same run are plotted against gradient steps and wall-clock time.',problems:['experiment_log'],test:'Prepare an experiment log and both step- and wall-clock-indexed learning curves.',check:['Can another person reproduce the run from your log?','When might a run look better by steps but worse by wall-clock time?']
},
{
 id:'tinystories',chapter:'07 · Experiments',section:'§7.2–7.2.3',page:39,title:'Establish a TinyStories baseline',goal:'Tune learning rate and batch size, then connect numerical loss to generated text.',
 explain:['TinyStories is intentionally simple enough to reveal model behavior quickly. Begin with a reproducible baseline, sweep learning rate while watching for divergence, and vary batch size with fair budgets and retuned settings where needed.','Generation gives qualitative evidence that complements validation loss. Keep the checkpoint and decoder settings with every sample. The PDF specifies a standard target and a lower-resource route; report which regime you used.'],concepts:['Official baseline configuration includes a 10K tokenizer, context length 256, d_model 512, d_ff 1344, and RoPE θ=10000.','The standard TinyStories target is validation loss ≤1.45; the handout permits a reduced-run target of 2.00 for CPU/MPS.','Edge-of-stability exploration requires at least one divergent run and careful comparison of convergence.'],formulas:[E('U13',String.raw`\operatorname{PPL}=e^{\bar\ell},\qquad \text{budget}=B\,T\,N_{\mathrm{steps}}`, 'Report both an interpretable evaluation metric and the number of training tokens when comparing runs.', 'The same tokenizer and validation split are required for meaningful loss/PPL comparisons.', 'A qualitative sample cannot replace the recorded validation curve.')],diagram:'tinystories',diagramAlt:'Several learning-rate curves on TinyStories show slow progress, good convergence, and divergence, with a separate generated-text checkpoint.',problems:['learning_rate','batch_size_experiment','generate'],test:'Deliver learning curves, tuned baseline checkpoint, and the required generation sample and discussion.',check:['Which factors besides architecture can explain different loss curves?','Why is a generated sample insufficient as the only evaluation?']
},
{
 id:'ablations',chapter:'07 · Experiments',section:'§7.3',page:42,title:'Ablate normalization, position, and gating',goal:'Use controlled changes to understand what each Transformer component contributes.',
 explain:['The handout asks for four comparisons: remove RMSNorm, move normalization after the sublayer, remove RoPE, and replace gated SwiGLU with a plain SiLU FFN. Each comparison should have its own learning curve and concise interpretation.','Ablation results depend on learning rate, model size, and training budget. The plain SiLU comparison uses a different inner width to keep parameter counts more comparable, so compare the stated baselines rather than arbitrary widths.'],concepts:['Pre-norm and post-norm move normalization relative to residual addition.','NoPE removes explicit positional rotation; causal structure may still supply some positional cues.','SwiGLU and SiLU differ in gating and parameter count.'],formulas:[E(25,String.raw`z=x+\operatorname{MHSA}(\operatorname{RMSNorm}(x))`, 'The first pre-norm residual branch normalizes before attention.', 'x and z share the residual-stream shape.', 'Compare the location of RMSNorm with equation (27).'),E(26,String.raw`y=z+\operatorname{FFN}(\operatorname{RMSNorm}(z))`, 'The second pre-norm residual branch normalizes before the FFN.', 'z and y share model width.', 'Both branches keep an unnormalized residual path.'),E(27,String.raw`z=\operatorname{RMSNorm}(x+\operatorname{MHSA}(x))`, 'Post-norm applies normalization after attention and residual addition.', 'The operation order changes gradient flow through the residual stream.', 'Compare with equation (25) under a controlled experiment.'),E(28,String.raw`y=\operatorname{RMSNorm}(z+\operatorname{FFN}(z))`, 'Post-norm likewise normalizes after the FFN residual addition.', 'z and y still have the same shape.', 'The two branches should be compared as an architecture, not mixed accidentally.'),E(29,String.raw`\operatorname{FFN}_{\mathrm{SiLU}}(x)=W_2\operatorname{SiLU}(W_1x)`, 'The ungated comparison removes the second SwiGLU branch.', 'W₁ expands from d_model; W₂ returns to d_model.', 'The handout adjusts d_ff for a more comparable parameter budget.')],diagram:'ablations',diagramAlt:'Four parallel comparison tracks show RMSNorm removal, pre- versus post-norm, RoPE versus NoPE, and SwiGLU versus SiLU.',problems:['layer_norm_ablation','pre_norm_ablation','no_pos_emb','swiglu_ablation'],test:'Submit paired curves and explanations for each PDF §7.3 ablation.',check:['What else must be controlled before attributing a result to a removed component?','How does pre-norm differ from post-norm in operation order?']
},
{
 id:'owt',chapter:'07 · Experiments',section:'§7.4',page:44,title:'Transfer the pipeline to OpenWebText',goal:'Interpret a harder corpus without treating its loss as directly comparable to TinyStories.',
 explain:['OpenWebText is broader and less predictable than children’s stories. The handout asks for an LM run with the same architecture and total iterations as the TinyStories experiment, along with curves and generated text.','Any loss comparison must account for tokenizer, data diversity, and the amount of training received. A worse-looking sample under the same budget may reflect task difficulty rather than a broken implementation.'],concepts:['Use the trained OpenWebText tokenizer and its corresponding encoded data.','Report the same measurement axes and decoder settings used for the TinyStories comparison.','Inspect samples alongside quantitative validation.'],formulas:[E('U0g',String.raw`\text{training tokens}=B\,T\,N_{\mathrm{steps}}`, 'Matching steps only matches the nominal token budget when batch and context length also match.', 'B is batch size, T is context length, and N_steps is optimizer updates.', 'Even equal token budgets do not make losses directly comparable across different tokenizers and corpora.')],diagram:'owt',diagramAlt:'The same model and training budget branch to TinyStories and OpenWebText, producing different validation curves and text diversity.',problems:['main_experiment'],test:'Provide the OWT curve, sample text, and the requested interpretation in PDF §7.4.',check:['Why is equal iteration count not the same as equal corpus difficulty?','Which tokenizer facts must accompany a cross-corpus loss comparison?']
},
{
 id:'leaderboard',chapter:'07 · Experiments',section:'§7.5',page:45,title:'Finish and audit the submission',goal:'Understand the leaderboard constraints and verify every required artifact before packaging.',
 explain:['The current handout permits only the provided OpenWebText training data for the leaderboard and limits one run to 45 minutes on a B200. It asks for final validation loss, a clearly time-indexed curve, and a description of changes.','The course submission includes typeset writeup.pdf and code.zip. Audit every Problem ID against its requested evidence; keep large datasets and checkpoints out of the code archive. Check the current leaderboard repository for submission mechanics.'],concepts:['Benchmark changes on small runs before spending the full compute budget.','Report what changed, what was held fixed, and the actual run time.','A completed code test suite does not substitute for written and experimental deliverables.'],formulas:[E('U14',String.raw`\text{run time}\le45\text{ minutes on one B200}`, 'This is the current leaderboard wall-clock constraint in the supplied handout.', 'The associated curve must visibly use wall-clock time on its horizontal axis.', 'Consult the latest official rules when submitting, because leaderboard requirements can change.')],diagram:'leaderboard',diagramAlt:'A final audit checklist brings together unit tests, writeup, code archive, learning curves, and leaderboard record.',problems:['leaderboard'],test:'Run uv run pytest; audit 38 Problem IDs; inspect writeup.pdf and code.zip; review leaderboard README.',check:['What evidence is still missing if every unit test passes?','Which constraint applies to the leaderboard run rather than to all self-study runs?']
}
];
